### ISSUE TITLE
db_location config

### ISSUE THREAD

**Issue by robert-wallis** [QCoDeS/Qcodes#1040]
Our exiting, working initialization code now encounters an error from a clean install without an environments.db file.

This may block Dave and Soheil in Delft tomorrow/tonight.

How can we initialize it correctly?

### Steps to reproduce
1. `from qcodes import config`
2. `from qcodes.dataset.data_export import get_shaped_data_by_runid`

### Expected behaviour
No error.

### Actual behaviour
`qcodes.config["core"]["db_location"]` is unset

`KeyError: 'db_location'`

![screen shot 2018-04-10 at 8 30 35 pm](https://user-images.githubusercontent.com/145938/38590439-072042ca-3ce6-11e8-8ec0-87270fbed144.png)

### System
**operating system**
Windows 10

**qcodes branch**
1.10

**qcodes commit**
 497fa48 (release on pip)

**Comment by jenshnielsen** [comment]
The config file bundled with Qcodes has that variable set https://github.com/QCoDeS/Qcodes/blob/master/qcodes/config/qcodesrc.json I suspect that you have another older file lying around somewhere. AFAIK it loads from user home directory as well as the one bundled in QCodes

**Comment by jenshnielsen** [comment]
or in cwd

**Comment by WilliamHPNielsen** [comment]
Yes, the hierarchy is

1. The `qcodesrc.json` in cwd
2. The `qcodesrc.json` in home
3. The `qcodesrc.json` in `qcodes/qcodes/config`

**Comment by jenshnielsen** [comment]
It looks like the config file bundled in the whl binary package is out of date for some reason. I think we will have to do a new release. For now you can get the tar.gz by installing qcodes with `pip install --no-binary qcodes qcodes` which does not seems to have this issue

**Comment by jenshnielsen** [comment]
or get the file json file (and schema) from the repo and put in user home or cwd

**Comment by WilliamHPNielsen** [comment]
@robert-wallis I just put out a new release, v0.1.11. Does using that resolve your issue?

**Comment by robert-wallis** [comment]
Yes @geoffroth just confirmed the 1.11 release fixed this. 🎉 

Thank you for the speedy release! 🙏

**Comment by jenshnielsen** [comment]
Great for the record #1044 should make it easier to spot this kind of issue
