### ISSUE TITLE
Driver/AWG5208 minor issues

### ISSUE THREAD

**Issue by WilliamHPNielsen** [QCoDeS/Qcodes#1060]
The current Tektronix 5208 driver has a few quirks.

- The validator for channel amplitudes is wrong
- A corrupt `.seqx` file is **not** overwritten by `sendSEQXFile` leading to a lot of hair pulling ("but this code generating a file worked a minute ago!")
- A sequence loaded into memory is not overwritten when loaded a second time even though the `.seqx` file changed
- The marker stopped value is missing
- The marker range is wrong, should be +/- 1.75 V

**Comment by WilliamHPNielsen** [comment]
Also, there should be a run state (`AWGCONTROL:RSTATE?`) parameter.

**Comment by ThorvaldLarsen** [comment]
@WilliamHPNielsen would it be possible to add a Wait_For_Run function (maybe with a better name) that waits until the AWG is running:
```
def Wait_For_Run(self):
    while self.ask('AWGCONTROL:RSTATE?') == '0':
        time.sleep(0.1)
```
