### ISSUE TITLE
Default title in `plot_by_id`

### ISSUE THREAD

**Issue by WilliamHPNielsen** [QCoDeS/Qcodes#1067]
Here's a suggestion: why don't we give the plots produced by `plot_by_id` a default title which contains their ID? That will make it easy to find the data based on a plot.

@Dominik-Vogel

**Comment by Dominik-Vogel** [comment]
That sounds like a good idea, we should also add the sample name and station name

**Comment by astafan8** [comment]
Solved in https://github.com/QCoDeS/Qcodes/pull/1235.
