### ISSUE TITLE
register_parameter always assumes 'numeric' type 

### ISSUE THREAD

**Issue by sohailc** [QCoDeS/Qcodes#1108]
Register parameter always uses paramtype='numeric' when creating the ParamSpec, regardless of the type of parameter to be registered. This is problematic when we try to register array-valued parameters.

A proposed solution is to check the parameter type. As a side note, using the ArrayParameter is undesirable as the shape of the array needs to be specified beforehand; this is a different, albeit related issue. 

A work around is to use ParamSpec directly and not use 'register_parameter'. We can add the ParamSpec manually to the data set.

**Comment by WilliamHPNielsen** [comment]
I think this is indeed a bug, but let me add a bit of background before we turn everything back into arrays.

At some point we agreed to convert ("unravel" was the word, if I remember correctly) arrays into numbers to avoid having binary blobs in the database. For a 2D sweep of, say, `V1` and `V2` with a signal `Y`, that entails converting what would be a table

 V1 | V2 | Y
----|-----|-------
   0  |   BLOB  | BLOB
   1  |  BLOB  | BLOB

into a table more like

 V1 | V2 | Y
----|-----|-------
   0  |  0  | 0.123
   0  |  1  | 0.234
   0 |   2  |  1.342
   1 |  0  |  -.231

That's probably good to keep in mind when solving this issue.

**Comment by nataliejpg** [comment]
I would also add to this that MultiChannel parameters dont currently work with add_parameter, also perhaps this is written somewhere but is there a function to get the data out of the database if it is saved as a binary blob? get_data and get_values didn't work for me? mention of both also in #1200
