### ISSUE TITLE
Settable parameters as context managers

### ISSUE THREAD

**Issue by cgranade** [QCoDeS/Qcodes#1117]
It might be useful for parameters which can be set to act as context managers, such that user code can be guaranteed that a parameter is returned to its original value after a block of code. For instance:

```python
>>> v = dac.voltage()
>>> with dac.voltage(-1):
...     # Do stuff with the DAC output set to -1 V.
...
>>> assert abs(dac.voltage() - v) <= tolerance
```
@QCoDeS/core

**Comment by sohailc** [comment]
Sohail & Mikhail will take a stab

**Comment by sohailc** [comment]
working on branch https://github.com/sohailc/Qcodes/tree/feature/settable_parameters
