### ISSUE TITLE
Keithley 2400 does not get added to the station cleanly

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#1149]
The ":read:" command and possibly others does not work when output is off but fails with an error. This is called when getting volt and current are snapshotted 

We should wrap these calls in checking that output is off

**Comment by spxtr** [comment]
I ran into this. For now the easy workaround is to add `keithley.output.set(1)` before adding it to a station or reading any values. Otherwise you'll see error 803 and it'll be borked until you restart it.
