### ISSUE TITLE
Request for complex numbers in database

### ISSUE THREAD

**Issue by ThorvaldLarsen** [QCoDeS/Qcodes#1158]
More and more data measured is inherently complex numbers so would like to request that the database can handle them directly. After our discussion last week in Delft it is clear that both sites would benefit from this capability.
This will of course also affect the plotting tool as we would like to be able to plot complex data along different axis (mag/phase, imag/real, or rotated axis).

I thought we can use this issue to discuss the whether this is a possibility or not.

@jenshnielsen  @wpfff @nataliejpg

**Comment by jenshnielsen** [comment]
Of relevance http://sqlite.1065341.n5.nabble.com/Thoughts-on-storing-arrays-of-complex-numbers-td81761.html

**Comment by ThorvaldLarsen** [comment]
Interesting read. I know next to nothing about database storage so cant really comment on the implementation or how complicated it is.
However, it does seem to me that qcodes should handle complex numbers rather than everyone coming up with separate ad hoc solutions to store/open two real numbers instead of a single complex number.

**Comment by astafan8** [comment]
Following PRs address this:
https://github.com/QCoDeS/Qcodes/pull/1592
https://github.com/QCoDeS/Qcodes/pull/1568
https://github.com/QCoDeS/Qcodes/pull/1493
https://github.com/QCoDeS/Qcodes/pull/1489
https://github.com/QCoDeS/Qcodes/pull/1484
