### ISSUE TITLE
Config can only use certain files

### ISSUE THREAD

**Issue by nataliejpg** [QCoDeS/Qcodes#1223]
It is possible to load a config from a specified file (returning the config in dictionary form) 

`cfg = Config()`
`cfg.load_config('some_path_here')`

and it is possible to update the config (which looks in the cwd, the env and the home directory)

`cfg.update()` 

but the combined version of these where you specify the location of the config file you want to use as current_config doesn't exist. Is there a strong reason for this?

**Comment by jenshnielsen** [comment]
I think this is sensible. Probably load_config should have been a private method all along. It seems somewhat problematic in that it updates the path to the config file in the class but not the actual config file.  

I suggest extending update_config to take an optional file path that would be loaded as the last config file.
