### ISSUE TITLE
Unnecessary numpy version restriction

### ISSUE THREAD

**Issue by terrorfisch** [QCoDeS/Qcodes#1270]
Currently the numpy version is restricted to be <1.14 as h5py was incompatible with it.

This has been fixed in h5py>=2.8: [Release Notes](http://docs.h5py.org/en/latest/whatsnew/2.8.html) / [github issue](https://github.com/h5py/h5py/issues/969)

**Comment by astafan8** [comment]
This is going to be fixed in https://github.com/QCoDeS/Qcodes/pull/1120 PR.

**Comment by terrorfisch** [comment]
Fixed
