### ISSUE TITLE
Rewrite Offline Plotting Tutorial to use Measurement and DataSaver instead of DataSet

### ISSUE THREAD

**Issue by astafan8** [QCoDeS/Qcodes#1274]
Current way `Offline Plotting Tutorial` is written, confuses users, as they think that they should use `DataSet` directly, while the preferred way is to use `Measurement` object and `with measurement.run() as datasaver: ...` context manager construct.

Hence the notebook should be rewritten to reflect the preferred approach. The `DataSet` approach can be preserved in an appendix of the notebook.

**Comment by WilliamHPNielsen** [comment]
Hear, hear! The dataset documentation needs a clean-up where we make it clear that the `Measurement` object is *the way* to save data. I don't think we even need examples of using the dataset directly, as long as we document the API.

**Comment by astafan8** [comment]
Shall I rename the issue then, and make improving `Offline Plotting Tutorial` as a sub-task? :)

**Comment by WilliamHPNielsen** [comment]
That'd be spot on.

**Comment by jenshnielsen** [comment]
In addition to the above it is really slow to run adding around 10 min to the docs build time on Azure pipelines

**Comment by WilliamHPNielsen** [comment]
Okay, let me take this one.
