### ISSUE TITLE
Driver / Infiniium oscilloscope : feature requests

### ISSUE THREAD

**Issue by WilliamHPNielsen** [QCoDeS/Qcodes#1335]
As requested by our friends in Sydney.

They would love:

1. To have a way to use the streaming method for large number of points as it is possible to hit the 1GB limit.
2. For the get trace to return the current trace not to trigger and wait. (don't use DIGITIZE)
3. The sin(x)/x interpolation to be disabled so number of points requested = the number of points returned
4. To have functions to control the state of the scope ie Run, Single, Stop
5. A function to block until the scope has been triggered and acquired its data/number of averages. using ESR/STB polling or equivalent instead of *OPC? and a long timeout as the scope becomes unresponsive if we decide to interrupt the program.
6. For the `trace` command not to change the acquisition mode to real-time. It shouldn't be reset every time `get_raw()` is called, since the scope may be in equivalent-time or high-res mode

@StevenWaddy @Dominik-Vogel

**Comment by WilliamHPNielsen** [comment]
In doing this, me may want to keep #1147 in mind.

**Comment by StevenWaddy** [comment]
Streaming mode will work for all lengths of data so is there a reason to keep the non-streaming mode?
Its also worth noting that splitting the acquisition and the transfer is the only way to read multiple traces captured at the same moment in time. So I may call the acquire command, then call the transfer command for each channel I care about.

Also with issue #1147<https://protect-au.mimecast.com/s/sig2CROAQotAolXysNkg6w?domain=github.com>. It wasn't present in the original driver / the derivatives in use in Sydney. The only differences I can see are the Sydney driver uses streaming mode and I also manipulated the raw data by hand so it may be an issue with non-streaming or the pyvisa binary query command.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by neildick** [comment]
Sorry to bump this, but I'm about to start some new measurements using this scope. Did you guys have a chance to look at some of these features?
