### ISSUE TITLE
DataSet.get_data: retrieving parts of dataset - actual start value depends on end

### ISSUE THREAD

**Issue by wpfff** [QCoDeS/Qcodes#1384]
i encountered the following just now when trying to load only part of a dataset using get_data: the start index that's actually returned depends on whether the end index has been supplied or left as `None`.

example screenshot:

![image](https://user-images.githubusercontent.com/892193/48586699-eedd9080-e930-11e8-920c-7da93570edae.png)

my expected behavior would be that the first element returned should not depend on the value of `end`.

**Comment by WilliamHPNielsen** [comment]
A note for @QCoDeS/core: this is another thing we must remember to refactor. Currently the start and end are directly inserted into the data fetching SQL query. For reading data from another source, this must be generalized.

@wpfff it's hard for me to asses the utility of this partial loading. Is it a feature you find useful?
