### ISSUE TITLE
Make qcodes.github.io point to documentation

### ISSUE THREAD

**Issue by StefanD986** [QCoDeS/Qcodes#1394]
Having to type http://qcodes.github.io/Qcodes/ to get to the qcodes docs seems a bit verbose to me. Only pointing the browser to http://qcodes.github.io throws a 404 error.

Is there any reason why qcodes.github.io does not point to the docs directly?

**Comment by jenshnielsen** [comment]
I think it is fair that  http://qcodes.github.io points to something useful. But I think it should be a table of content that points to the QCoDeS documentation as we have multiple packages within the QCoDeS organization we probably don't what that url to just point to the QCoDeS docs

**Comment by Akshita07** [comment]
Now we have a nice page at http://qcodes.github.io
