### ISSUE TITLE
Documentation error v0.1.11: load_or_create_experiment

### ISSUE THREAD

**Issue by jsaez8** [QCoDeS/Qcodes#1448]
Hello, thank you for this awesome library. I am using it for my master thesis at Universidad Autónoma de Madrid (Spain) and find it really useful. While learning I have found an error in the documentation.

I am using qcodes v0.1.11 (last version I have been able to install with pip using your instructions (http://qcodes.github.io/Qcodes/start/index.html#installing-the-latest-qcodes-release). When I check the documentation of this version I can see there is a function `load_or_create_experiment` (http://qcodes.github.io/Qcodes/api/generated/qcodes.dataset.experiment_container.load_or_create_experiment.html) However, I cannot import it in qcodes.

### Steps to reproduce
```python
sys.version

'3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]'

import qcodes
qcodes.__version__
'0.1.11'

from qcodes.dataset import experiment_container
experiment_container.load_or_create_experiment()
    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    <ipython-input-16-44f48f692e42> in <module>
    ----> 1 experiment_container.load_or_create_experiment()
    

    AttributeError: module 'qcodes.dataset.experiment_container' has no attribute 'load_or_create_experiment'
```

### Expected behaviour

I am still a novice with github and qcodes but I have been able to find that this function was introduced last summer while the last release of qcodes dates from April. Thus, I would expect not to see this function in the documentation of v0.1.11. This might be happening also for other new features, but I haven't explored further.

If I want to use these new features, would you recommend me to clone the github repo and install it from source or are you planning to make a new release soon?

**Comment by astafan8** [comment]
Thanks for your feedback! :)

Yes, we haven't been doing `pip` releases because of a ton of work lately. So, for now, just follow http://qcodes.github.io/Qcodes/start/index.html#installing-qcodes-from-github to have the latest qcodes with all the latest updates.
