### ISSUE TITLE
default subscriber for plottr does not work for its new version

### ISSUE THREAD

**Issue by astafan8** [QCoDeS/Qcodes#1457]
For implementing live plotting, the new `plottr` monitors the database file directly, without using the subscribers, hence the information in [qcodes docs](http://qcodes.github.io/Qcodes/examples/plotting/live_plotting.html#Live-plotting-with-plottr-as-an-example) is not correct anymore.

See https://github.com/kouwenhovenlab/plottr/issues/36.

I suggest just to remove the mentioning of `plottr`, or substitute it with a link the exactly working version (which is now ["the old `plottr`"](https://github.com/kouwenhovenlab/plottr/releases/tag/original-final))

**Comment by Dominik-Vogel** [comment]
I agree - go for it!
Monitoring the db file is really all it takes.

**Comment by jenshnielsen** [comment]
Plottr no longer uses subscriptions
