### ISSUE TITLE
error when starting instrument driver

### ISSUE THREAD

**Issue by peendebak** [QCoDeS/Qcodes#146]
I encountered some issues with starting instrument drivers in the normal way (so not with  `server_name=None`). Reduced to a minimal example:

``` python
import time,sys
import qcodes
#qcodes.set_mp_method('spawn')  # force Windows behavior on mac

import qcodes.instrument_drivers.QuTech.IVVI

print('start test')

if __name__ ==  '__main__'  :
    time.sleep(3)
    print( 'start driver with server_name empty string' )
    ivvi1 = qcodes.instrument_drivers.QuTech.IVVI.IVVI(name='ivvi1', address='ASRL3', numdacs=16, server_name='' )

print('done' )
```

The output of the script is:

```
start test
start driver with server_name empty string
start test
done
Initialized IVVI-rack in 0.30s
done
```

Why is the script executed twice? If I remove the  `if __name__ ==  '__main__'  :` condition, then the script generates an error when starting the IVVI driver. This error message gives no clue what is going on, so it is hard to debug.

**Comment by giulioungaretti** [comment]
Closed because the multiprocessing implementation proved to be too buggy and thus ⚡️ 'ed.
