### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by AdriaanRol** [QCoDeS/Qcodes#1571]
@astafan8 

### Steps to reproduce
1. Go to: https://qcodes.github.io/Qcodes/user/faq.html
2. Click on the link `examples`. This links to : https://qcodes.github.io/Qcodes/user/docs/examples/Tutorial.ipynb
3. Get a 404 error 

### Expected behaviour
This should link to the example notebooks directory either on some online hosting like binder or to the path on github. 

### Actual behaviour
A 404 error

**Comment by Akshita07** [comment]
This issue has been solved.

**Comment by Akshita07** [comment]
Sorry, my mistake. The issue is still open.
