### ISSUE TITLE
missing _vals and name

### ISSUE THREAD

**Issue by MerlinSmiles** [QCoDeS/Qcodes#166]
@alexcjohnson and others, 

I have a parameter:

``` Python
        self.add_parameter('fld',
                           names=['B'+ax.lower() for ax in self.axes],
                           get_cmd=partial(self._get_fld, self.axes, 'FLD'),
                           set_cmd=partial(self._ramp_to_setpoint, self.axes, 'FSET'),
                           units=['T'for ax in self.axes],
                           vals=Anything())
```

When I want to use this parameter:

``` Python
magnet.fld.set([0.8,0.1,0.0])
```

this fails.
At first qc complains that the parameter has no attribute `name` this is because I have supplied n names for n axes. If I add `self.name` in `parameter.py` that error goes away.
Then qc complains that the parameter has no attribute `_vals` which is also missing due to the names.
If I add that too, I can do what I planned.

in parameter.py I see:

``` Python
        if names is not None:
            # check for names first - that way you can provide both name
            # AND names for instrument parameters - name is how you get the
            # object (from the parameters dict or the delegated attributes),
            # and names are the items it returns

...
        elif name is not None:
```

That comment seems to contradict what is actually happening, should this just be `if` and `if` instead?

Btw, what is the correct validator for a list of numbers?

**Comment by jenshnielsen** [comment]
@MerlinSmiles I think this can close now? The current issue with Array/Multiparameters is that they are not settable #207 and the confusing setpoints #498

**Comment by MerlinSmiles** [comment]
@jenshnielsen I guess yes, there have been a lot of changes that resolve this, I think
