### ISSUE TITLE
Filename collision due to case-sensitivity in Keysight folder

### ISSUE THREAD

**Issue by spauka** [QCoDeS/Qcodes#1709]
When pulling the qcodes repository on Windows, there is a filename collision between the uppercase and lowercase Keysight folders.

The error message is as follows:
```bash
$ git clone https://github.com/QCoDeS/Qcodes.git
Cloning into 'Qcodes'...
remote: Enumerating objects: 1522, done.
remote: Counting objects: 100% (1522/1522), done.
remote: Compressing objects: 100% (655/655), done.

Receiving objects: 100% (112398/112398), 242.65 MiB | 2.58 MiB/s, done.
Resolving deltas: 100% (87395/87395), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'qcodes/instrument_drivers/Keysight/__init__.py'
  'qcodes/instrument_drivers/keysight/__init__.py'
```

I propose we remove the lowercase keysight folder as it has now been deprecated for over 2 years.

### System
Windows/OSX and other OS's with case insensitive file systems.

**Comment by astafan8** [comment]
i'm working on macOS and haven't seen this problem. But i'm all for removing that lowercase directory if it is possible in a clean way.

**Comment by jenshnielsen** [comment]
@astafan8 Please see the discussion of the issues in #1710

**Comment by astafan8** [comment]
@jenshnielsen thanks, already curiously following it :)
