### ISSUE TITLE
Bug in DelegateParameter: get_latest and set_cache are not forwarded to source parameter

### ISSUE THREAD

**Issue by astafan8** [QCoDeS/Qcodes#1782]
See the following tests of `DelegateParameter` that are marked as `xfail`: https://github.com/QCoDeS/Qcodes/pull/1757/commits/b04266b94ff362d0829cdbd8d3215ca557009e2d ([on master around here](https://github.com/QCoDeS/Qcodes/blob/master/qcodes/tests/test_parameter.py#L1743-L1844))

Expectation: `DelegateParameter`s `get_latest` and `set_cache` should in principle simply forward the call to `get_latest` and `set_cache` of the source parameter.

**Comment by Dominik-Vogel** [comment]
I think it is more involved than that. At the example of the `scale` of a parameter, consider the following:
![DelegateParameter_cached](https://user-images.githubusercontent.com/30660470/68479958-db0ef680-0233-11ea-8beb-226b06f6eb84.png)
[2:31 PM] Dominik Vogel (Adecco)
It seems that set_cached needs calculate the raw value, and forward that to set_cached of the original parameter.
`get_latest` of the delegate parameter should convert its raw value, which is received by calling into get_latest of the source, to the non-raw value.
I will need to look into #1757 again to refresh my knowledge of the new caching mechanism. Then I can implement the cache for the `DelegateParameter` next week.

**Comment by Dominik-Vogel** [comment]
Plan of actions agreed upon with @astafan8 
1) Merge PR #1791, removing all uses of self._latetst ouside the actual getters/setters
2) Repair Delegate Parameter
3) Create new PR to move ._latest into seperate class to make clear that the scope of the private attribute is only for getters and setters
