### ISSUE TITLE
Module file names

### ISSUE THREAD

**Issue by MerlinSmiles** [QCoDeS/Qcodes#181]
Within Qcodes we have some files that may conflict with standard libs.
i.e. in the `plots` folder we have `matplotlib` and `pyqtgraph`, in the `utils` we have `threading`, in `instruments` we have `visa`, and there may be more.
The Issue I see with this is that if I want to add another file that uses the original libraries, I cant import them. I.e. If I make a new plotting thing, I cant import `pyqtgraph` as it tries to import from the file in the same directory.

```
ImportError: No module named 'pyqtgraph.multiprocess'; 'pyqtgraph' is not a package
```

Along with this, I see several `base.py` files, which can be slightly confusing, it would be nice if they had clear names too.

What do you guys think?
cc @alexcjohnson @giulioungaretti @AdriaanRol

**Comment by giulioungaretti** [comment]
closing this for now. It will eventually taken care of :D 
As long as the class names are the same there won't be many problems.
Unless people decided on purpose  to not use the qcodes namespace.
So if you did the right thing:
  
``` from qcodes import MatPlot```

then your are safe. If you  did this instead: 

```  from qcodes.plots.qcmatplotlib import matplot``` 

You'll have to refactor.
