### ISSUE TITLE
ATS9870 incorrect default value in driver

### ISSUE THREAD

**Issue by abargerbos** [QCoDeS/Qcodes#1829]
### Steps to reproduce
Upon loading the Alazar driver (ATS9870.py) an error is thrown regarding setting the external trigger coupling. After some investigation it seems that by default 'external_trigger_coupling' is set to 'AC'. However, the only supported value for this card is 'DC'. As far as we can tell this is not a recent change in qcodes, it has been present since the first version of the ATS9870 driver.

Please either set the initial value to 'DC', or rather just remove the 'AC' option for this card and remove the external_trigger_coupling parameter altogether. 

### System
**operating system**
Windows 10

**Comment by lakhotiaharshit** [comment]
@Dominik-Vogel
