### ISSUE TITLE
Links to issues on Contributing page point to forked repository

### ISSUE THREAD

**Issue by sldesnoo-Delft** [QCoDeS/Qcodes#1917]
Contributing page has links to the issues on GitHub. These links do not link to QCoDeS/Qcodes repository, but to the qdev-dk/Qcodes fork.

See:
https://github.com/QCoDeS/Qcodes/blob/master/CONTRIBUTING.rst#bugs-reports-and-feature-requests

**Comment by lakhotiaharshit** [comment]
Thanks for pointing this out!
