### ISSUE TITLE
Names for DeferredOperations

### ISSUE THREAD

**Issue by alexcjohnson** [QCoDeS/Qcodes#222]
We can currently construct calculated parameters out of existing parameters, by way of the `DeferredOperations` framework. But to make this useful in loops and plots, you need to separately provide `name` and `label`:

``` python
cond = (meter.volt - meter.voffset) * preamp.sens * 25812.8 / source.volt
cond.name = 'cond'
cond.label = 'Conductance (e^2/h)'

Loop(...).each(cond)
```

So the questions are:
- Should we try and automatically generate a name, so you can use these in loops without error no matter what, or is it only allowed with an explicit name?
- Do we want an inline syntax, such as `Loop(...).each((meter.volt / source.volt).named('cond'))` so people can create parameters completely inline, or is it OK to require these to be separate statements? I suppose if we implement #26 then these can be kwargs to `Get`.

**Comment by giulioungaretti** [comment]
@MerlinSmiles  I wonder, how much easier this is that really using a new parameter ?

**Comment by MerlinSmiles** [comment]
@giulioungaretti I wonder the same.
just adds the amount of data in the dataset instead of having an on the fly calculation, as I wont want to nuke the raw data.
If its about me you can close this thing...

**Comment by jenshnielsen** [comment]
We have deprecated deferred operation
