### ISSUE TITLE
Qcodes driver error: InstrumentChannel parameters are not the attributes to the parent instrument?

### ISSUE THREAD

**Issue by Saba-Mehshar** [QCoDeS/Qcodes#2231]
Hi, I have been trying to use a qcodes driver for the Network Analyzer but getting an attribute error. My Instrument Channel has a parameter called 'magnitude', but it does not get bind to the parent instrument and giving this error when I try to measure it: 

AttributeError                            Traceback (most recent call last)

<ipython-input-4-753c436e1d0b> in <module>
      1 # Run a measurement
      2 meas = Measurement()
----> 3 meas.register_parameter(vna.magnitude)
      4 
      5 with meas.run() as datasaver:

~\.conda\envs\qcodes\lib\site-packages\qcodes\utils\helpers.py in __getattr__(self, key)
    396         raise AttributeError(
    397             "'{}' object and its delegates have no attribute '{}'".format(
--> 398                 self.__class__.__name__, key))
    399 
    400     def __dir__(self):

AttributeError: 'NetworkAnalyser_S5048' object and its delegates have no attribute 'magnitude'

However, I have no trouble when setting the parameters which are added to the parent instrument. If anyone knows how to bind the Instrument channels with the main instrument, then please respond to this issue.
Many thanks in advance.

**Comment by jenshnielsen** [comment]
Hi @Saba-Mehshar 
Hi @Saba-Mehshar 

Is there a particular reason why it needs to be bould to the instrument. 
Normally I would just supply the full path to the parameter.
`vna.channel.magnitude` where channel is the name that your channel is registered under. 

A few more questions to help understand what is going on. 

* Which exact VNA is this. The R&S driver from qcodes? 
* If you just do `vna.magnitude.get()` does the that error in the same way.

**Comment by Saba-Mehshar** [comment]
Hi @jenshnielsen 
Thank you very much for your quick response!

I have used the both vna.channel.magnitude and vna.magnitude.get() , yet getting the similar attribute error.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-d6aa0f5e0f28> in <module>
----> 1 vna.magnitude.get()

~\.conda\envs\qcodes\lib\site-packages\qcodes\utils\helpers.py in __getattr__(self, key)
    396         raise AttributeError(
    397             "'{}' object and its delegates have no attribute '{}'".format(
--> 398                 self.__class__.__name__, key))
    399 
    400     def __dir__(self):

AttributeError: 'NetworkAnalyser_S5048' object and its delegates have no attribute 'magnitude'


This is a copper mountain S5048 2-Port 4.8 GHz Analyzer, and I have been using a Qcodes  Keysight Network Analyzers  N5245A driver (have only made fewer changes). I can control my VNA with this driver (frequency, bandwidth and power etc.) and have never got any issue but cannot plot the results.
This is how my code looks like in jupyter notebook:

"" import logging
import matplotlib.pyplot as plt


import qcodes as qc
from qcodes.dataset.experiment_container import new_experiment, load_experiment_by_name
from qcodes.dataset.measurements import Measurement
from qcodes.dataset.plotting import plot_by_id
import qcodes.instrument_drivers.networkanalyser.NetworkAnalyser_S5048 as NetworkAnalyser_S5048
from qcodes.instrument.specialized_parameters import ElapsedTimeParameter

logger = logging.getLogger()



exp_name = 'VNA_Example'
sample_name = '2'
try:
    exp = load_experiment_by_name(exp_name, sample=sample_name)
    print('Experiment loaded. Last ID no:', exp.last_counter)
except ValueError:
    exp = new_experiment(exp_name, sample_name)
    print('Starting new experiment.')

Experiment loaded. Last ID no: 68


vna = NetworkAnalyser_S5048.NetworkAnalyser_S5048('vna', 'TCPIP0::localhost::5025::SOCKET')

Connected to: CMT S5048 (serial:14027062, firmware:19.3.0/2) in 0.10s


vna.power(-20)
vna.start(20e3)
vna.stop(2e9)
vna.points(1000)
vna.active_trace(1)
vna.if_bandwidth(2e3)
vna.averaging(True)
vna.average_factor(3)""

No error up to this point. I think my instrument channel is not added to the parent instrument. I can send you the driver code if needed.
I have been getting this error for a week but couldn't resolve it. Please give me some suggestions. Thank you very much.

**Comment by jenshnielsen** [comment]
As far as I can read from the driver of the N52xx I would expect that you need to use:

`vna.traces.magnitude` 

to get the values

**Comment by Saba-Mehshar** [comment]
Hi, I have got the following error

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-fd7c02c62372> in <module>
----> 1 vna.traces.magnitude

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument\channel.py in __getattr__(self, name)
    437         """
    438         # Check if this is a valid parameter
--> 439         if name in self._channels[0].parameters:
    440             setpoints = None
    441             setpoint_names = None

IndexError: list index out of range

**Comment by jenshnielsen** [comment]
Did you add a parameter to measure with the trace like here. https://qcodes.github.io/Qcodes/examples/driver_examples/Qcodes example with Keysight Network Analyzer.html?highlight=n5245a

```
pna.trace("S21")
```

**Comment by Saba-Mehshar** [comment]
Hi @jenshnielsen 

yes, I have added a parameter :  self.add_parameter('trace',
                                                         label='Trace',
                                                         get_cmd=self._Sparam,
                                                         set_cmd=self._set_Sparam)

but I am still getting the same attribute error:
AttributeError: 'NetworkAnalyser_S5048' object and its delegates have no attribute 'trace'

I think there is some problem with my Qcodes driver(I have made some changes in N5245A!). 

I am now trying to use 'QCoDeS driver for the HP 8753D Network Analyzer'. It seems to work a bit, but readable snapshot says, 'couldn't update s_parameter and display_format'. Because of this I am unable to take a trace.
Here is my output in Jupyter notebook:

%matplotlib notebook

import qcodes as qc
from qcodes.instrument_drivers.networkanalyser.VNAS504 import VNAS504
from functools import partial



VNA = VNAS504('VNA', 'TCPIP0::localhost::5025::SOCKET')



Connected to: CMT S5048 (serial:14027062, firmware:19.3.0/2) in 0.10s

VNA.reset()
VNA.print_readable_snapshot(update=True)   
  
[VNA(VNAS504)] Snapshot: Could not update parameter: s_parameter
[VNA(VNAS504)] Snapshot: Could not update parameter: display_format

VNA:
	parameter         value
--------------------------------------------------------------------------------
IDN                :	{'vendor': 'CMT', 'model': 'S5048', 'serial': '14027062'...
averaging          :	OFF 
display_format     :	None 
display_reference  :	0 
display_scale      :	10 
number_of_averages :	10 
output_power       :	0 (dBm)
s_parameter        :	None 
start_freq         :	30000 (Hz)
stop_freq          :	1e+09 (Hz)
sweep_time         :	0 (s)
timeout            :	5 (s)
trace              :	Not available 
trace_points       :	201 



# Let's get a single trace of S21 with 10 averages
# with a frequency range from 30 kHz to 1 GHz
# on a log scale
VNA.display_format('Log Mag')
VNA.s_parameter('S21')
VNA.start_freq(30e3)
VNA.stop_freq(1e9)

# and let's adjust the y-scale to fit
VNA.display_scale(0.12)
VNA.display_reference(-0.1)

# and finally enable averaging
VNA.averaging('ON')
VNA.number_of_averages(10)


# Now aquire a trace
VNA.trace.prepare_trace()  # this must be called prior to a Measurement or Loop
tracedata = qc.Measure(VNA.trace).run()  # this returns a dataset
plot = qc.MatPlot(tracedata.arrays['VNA_trace'])



# VisaIOError                               Traceback (most recent call last)
 <ipython-input-5-f49592598625> in <module>
      1 # Now aquire a trace
----> 2 VNA.trace.prepare_trace()  # this must be called prior to a Measurement or Loop
      3 tracedata = qc.Measure(VNA.trace).run()  # this returns a dataset
      4 plot = qc.MatPlot(tracedata.arrays['VNA_trace'])

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument_drivers\networkanalyser\VNAS504.py in prepare_trace(self)
     73         self.shape = (len(sps),)
     74 
---> 75         self.label = self._instrument.s_parameter()
     76         self.unit = _unit_map[self._instrument.display_format()]
     77 

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument\parameter.py in __call__(self, *args, **kwargs)
    390         if len(args) == 0:
    391             if self.gettable:
--> 392                 return self.get()
    393             else:
    394                 raise NotImplementedError('no get cmd found in' +

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument\parameter.py in get_wrapper(*args, **kwargs)
    583             except Exception as e:
    584                 e.args = e.args + ('getting {}'.format(self),)
--> 585                 raise e
    586 
    587         return get_wrapper

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument\parameter.py in get_wrapper(*args, **kwargs)
    570             try:
    571                 # There might be cases where a .get also has args/kwargs
--> 572                 raw_value = get_function(*args, **kwargs)
    573 
    574                 value = self._from_raw_value_to_value(raw_value)

~\.conda\envs\qcodes\lib\site-packages\qcodes\utils\command.py in __call__(self, *args)
    176             raise TypeError(
    177                 'command takes exactly {} args'.format(self.arg_count))
--> 178         return self.exec_function(*args)

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument_drivers\networkanalyser\VNAS504.py in _s_parameter_getter(self)
    281         """
    282         for cmd in ['S11?', 'S12?', 'S21?', 'S22?']:
--> 283             resp = self.ask(cmd)
    284             if resp in ['1', '1\n']:
    285                 break

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument\base.py in ask(self, cmd)
    753             inst = repr(self)
    754             e.args = e.args + ('asking ' + repr(cmd) + ' to ' + inst,)
--> 755             raise e
    756 
    757     def ask_raw(self, cmd: str) -> str:

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument\base.py in ask(self, cmd)
    746         """
    747         try:
--> 748             answer = self.ask_raw(cmd)
    749 
    750             return answer

~\.conda\envs\qcodes\lib\site-packages\qcodes\instrument\visa.py in ask_raw(self, cmd)
    225         with DelayedKeyboardInterrupt():
    226             self.visa_log.debug(f"Querying: {cmd}")
--> 227             response = self.visa_handle.query(cmd)
    228             self.visa_log.debug(f"Response: {response}")
    229         return response

~\.conda\envs\qcodes\lib\site-packages\pyvisa\resources\messagebased.py in query(self, message, delay)
    611         if delay > 0.0:
    612             time.sleep(delay)
--> 613         return self.read()
    614 
    615     def ask(self, message, delay=None):

~\.conda\envs\qcodes\lib\site-packages\pyvisa\resources\messagebased.py in read(self, termination, encoding)
    425         if termination is None:
    426             termination = self._read_termination
--> 427             message = self._read_raw().decode(enco)
    428         else:
    429             with self.read_termination_context(termination):

~\.conda\envs\qcodes\lib\site-packages\pyvisa\resources\messagebased.py in _read_raw(self, size)
    398                     logger.debug('%s - reading %d bytes (last status %r)',
    399                                  self._resource_name, size, status)
--> 400                     chunk, status = self.visalib.read(self.session, size)
    401                     ret.extend(chunk)
    402             except errors.VisaIOError as e:

~\.conda\envs\qcodes\lib\site-packages\pyvisa\ctwrapper\functions.py in read(library, session, count)
   1582     buffer = create_string_buffer(count)
   1583     return_count = ViUInt32()
-> 1584     ret = library.viRead(session, buffer, count, byref(return_count))
   1585     return buffer.raw[:return_count.value], ret
   1586 

~\.conda\envs\qcodes\lib\site-packages\pyvisa\ctwrapper\highlevel.py in _return_handler(self, ret_value, func, arguments)
    191 
    192         if ret_value < 0:
--> 193             raise errors.VisaIOError(ret_value)
    194 
    195         if ret_value in self.issue_warning_on:

VisaIOError: ('VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.', "asking 'S11?' to <VNAS504: VNA>", 'getting VNA_s_parameter')

Please give suggestion with this one because HP 8753D Network Analyzer is quite similar to my VNA. Thank you very much.

**Comment by jenshnielsen** [comment]
I am a bit confused. Are you trying to use a driver for first a Keysight and now an HP VNA for a instrument from a completly different vendor ? That is very unlikely to work. If you need a driver for the that instrument you will most likely have to write it from scratch. You may be lucky that some of the commands are the same but in general that is very unlikely to work

**Comment by Saba-Mehshar** [comment]
@jenshnielsen 

I have rewritten all the SCPI commands for Copper mountain (have written the driver from scratch!) but I have been following the script of Keysight/HP VNA Qcodes driver. Cannot I follow the script of these drivers?

**Comment by jenshnielsen** [comment]
The error that you show indicates that the instrument does not understand the command send when you execute `VNA.trace.prepare_trace()` so there is some kind of issue related to whatever you send to the instrument

**Comment by Saba-Mehshar** [comment]
Thanks @jenshnielsen .

Yes, there was two commands missing in my vna driver! 
I am now getting "AttributeError: module 'qcodes' has no attribute 'Measure'." This is how my output looks like:


%matplotlib notebook
import qcodes as qc
from qcodes.instrument_drivers.networkanalyser.VNAS504 import VNAS504
from functools import partial



VNA = VNAS504('VNA', 'TCPIP0::localhost::5025::SOCKET')
Connected to: CMT S5048 (serial:14027062, firmware:19.3.0/2) in 0.10s

VNA.reset()

VNA.print_readable_snapshot(update=True)

VNA:
	parameter         value
--------------------------------------------------------------------------------
IDN                :	{'vendor': 'CMT', 'model': 'S5048', 'serial': '14027062'...
averaging          :	OFF 
display_format     :	SWR 
display_reference  :	0 
display_scale      :	10 
number_of_averages :	10 
output_power       :	0 (dBm)
s_parameter        :	S22 
start_freq         :	20000 (Hz)
stop_freq          :	4.8e+09 (Hz)
sweep_time         :	0 (s)
timeout            :	5 (s)
trace              :	Not available 
trace_points       :	201 


VNA.display_format('Lin Mag')
VNA.s_parameter('S11')
VNA.start_freq(30e3)
VNA.stop_freq(1e9)
VNA.display_scale(0.12)
VNA.display_reference(-0.1)
VNA.averaging('ON')
VNA.number_of_averages(20)

VNA.print_readable_snapshot(update=True)



VNA:
	parameter         value (There is still no change in the snapshot - nothing is being updated)
--------------------------------------------------------------------------------
IDN                :	{'vendor': 'CMT', 'model': 'S5048', 'serial': '14027062'...
averaging          :	OFF 
display_format     :	SWR 
display_reference  :	0 
display_scale      :	10 
number_of_averages :	10 
output_power       :	0 (dBm)
s_parameter        :	S22 
start_freq         :	30000 (Hz)
stop_freq          :	1e+09 (Hz)
sweep_time         :	0 (s)
timeout            :	5 (s)
trace              :	Not available (dim. less)
trace_points       :	201 


VNA.trace.prepare_trace()  
tracedata = qc.Measure(VNA.trace).run()  
plot = qc.MatPlot(tracedata.arrays['VNA_trace'])



---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-f49592598625> in <module>
      1 # Now aquire a trace
      2 VNA.trace.prepare_trace()  # this must be called prior to a Measurement or Loop
----> 3 tracedata = qc.Measure(VNA.trace).run()  # this returns a dataset
      4 plot = qc.MatPlot(tracedata.arrays['VNA_trace'])

AttributeError: module 'qcodes' has no attribute 'Measure'



# This is my Qcodes driver:

from typing import Union
from functools import partial
import logging

import numpy as np

from qcodes.instrument.visa import VisaInstrument
from qcodes.instrument.parameter import ArrayParameter
import qcodes.utils.validators as vals

log = logging.getLogger(__name__)

_unit_map = {'Log Mag': 'dB',
             'Phase': 'degree',
             'Group Delay': None,
             'Smith': 'dim. less',
             'Polar': 'dim. less',
             'Lin mag': 'dim. less',
             'Real': None,
             'Imag': None,
             'SWR': 'dim. less'}


def CMTIntParser(value: str) -> int:
    """
    Small custom parser for ints

    Args:
        value: the VISA return string using exponential notation
    """
    return int(float(value))


class TraceNotReady(Exception):
    pass


class VNAS504Trace(ArrayParameter):
    """
    Class to hold a the trace from the S5048

    Although the trace can have two values per frequency, this
    class only returns the first value
    """

    def __init__(self, name, instrument):
        super().__init__(name=name,
                         shape=(1,),  # is overwritten by prepare_trace
                         label='',  # is overwritten by prepare_trace
                         unit='',  # is overwritten by prepare_trace
                         setpoint_names=('Frequency',),
                         setpoint_labels=('Frequency',),
                         setpoint_units=('Hz',),
                         snapshot_get=False
                         )

        self._instrument = instrument

    def prepare_trace(self):
        """
        Update setpoints, units and labels
        """

        # we don't trust users to keep their fingers off the front panel,
        # so we query the instrument for all values

        fstart = self._instrument.start_freq()
        fstop = self._instrument.stop_freq()
        npts = self._instrument.trace_points()

        sps = np.linspace(fstart, fstop, npts)
        self.setpoints = (tuple(sps),)
        self.shape = (len(sps),)

        self.label = self._instrument.s_parameter()
        self.unit = _unit_map[self._instrument.display_format()]

        self._instrument._traceready = True

    def get_raw(self):
        """
        Return the trace
        """

        inst = self._instrument

        if not inst._traceready:
            raise TraceNotReady('Trace not ready. Please run prepare_trace.')

        inst.write('CALC:FORM') 
        inst.write('CALC:DATA:FDAT')
        inst.visa_handle.read_termination = ''
        raw_resp = inst.visa_handle.read_raw()
        inst.visa_handle.read_termination = '\n'

        first_points = B''
        # 4 bytes header, 4 bytes per point, value1's and value2's
        # are intertwined like: val1_001, val2_001, val1_002, val2_002...
        for n in range((len(raw_resp)-4)//4):
            first_points += raw_resp[4:][2*n*4:(2*n+1)*4]

        dt = np.dtype('>f')
        trace1 = np.fromstring(first_points, dtype=dt)

        return trace1


class VNAS504(VisaInstrument):
    """
    This is the QCoDeS driver for the VNAS5048 Network Analyzer
    """

    def __init__(self, name: str, address: str, **kwargs) -> None:
        super().__init__(name, address, terminator='\n', **kwargs)

        self.add_parameter(
            'start_freq',
            label='Sweep start frequency',
            unit='Hz',
            set_cmd=partial(self.invalidate_trace, 'SENS:FREQ:STAR {} HZ'),
            get_cmd='SENS:FREQ:STAR?',
            get_parser=float,
            vals=vals.Numbers(20000, 4800000000))

        self.add_parameter(
            'stop_freq',
            label='Sweep stop frequency',
            unit='Hz',
            set_cmd=partial(self.invalidate_trace, 'SENS:FREQ:STOP {} HZ'),
            get_cmd='SENS:FREQ:STOP?',
            get_parser=float,
            vals=vals.Numbers(20000, 4800000000))

        self.add_parameter(
            'averaging',
            label='Averaging state',
            set_cmd='SENS:AVER{}',
            get_cmd='SENS:AVER?',
            val_mapping={'ON': 1, 'OFF': 0})

        self.add_parameter(
            'number_of_averages',
            label='Number of averages',
            set_cmd='SENS:AVER:COUN{}',
            get_cmd='SENS:AVER:COUN?',
            get_parser=CMTIntParser,
            vals=vals.Ints(0, 999))

        self.add_parameter(
            'trace_points',
            label='Number of points in trace',
            set_cmd=partial(self.invalidate_trace, 'SENS:SWE:POIN{}'),
            get_cmd='SENS:SWE:POIN?',
            get_parser=CMTIntParser,
            vals=vals.Enum(3, 11, 26, 51, 101, 201, 401,
                           801, 1601))

        self.add_parameter(
            'sweep_time',
            label='Sweep time',
            set_cmd='SENS:SWE:POIN:TIME{}',
            get_cmd='SENS:SWE:POIN:TIME?',
            unit='s',
            get_parser=float,
            vals=vals.Numbers(0, 0.3),
            )

        self.add_parameter(
            'output_power',
            label='Output power',
            unit='dBm',
            set_cmd='SOUR:POW{}',
            get_cmd='SOUR:POW?',
            get_parser=float,
            vals=vals.Numbers(-80, 20))
        
        self.add_parameter(
            's_parameter',
            label='S-parameter',
            set_cmd=self._s_parameter_setter,
            get_cmd=self._s_parameter_getter)


        # DISPLAY / Y SCALE PARAMETERS
        self.add_parameter(
            'display_format',
            label='Display format',
            set_cmd=self._display_format_setter,
            get_cmd=self._display_format_getter)

        # TODO: update this on startup and via display format
        self.add_parameter(
            'display_reference',
            label='Display reference level',
            unit=None,  # will be set by display_format
            get_cmd='DISP:WIND:TRAC:Y:RLEV?',
            set_cmd='DISP:WIND:TRAC:Y:RLEV{}',
            get_parser=float,
            vals=vals.Numbers(-500, 500))

        self.add_parameter(
            'display_scale',
            label='Display scale',
            unit=None,  # will be set by display_format
            get_cmd='DISP:WIND:TRAC:Y:PDIV?',
            set_cmd='DISP:WIND:TRAC:Y:PDIV{}',
            get_parser=float,
            vals=vals.Numbers(-500, 500))

        self.add_parameter(
            name='trace',
            parameter_class=VNAS504Trace)

        # Startup
        self.startup()
        self.connect_message()
        
    def reset(self) -> None:
        """
        Resets the instrument to factory default state
        """
        # use OPC to make sure we wait for operation to finish
        self.ask('*OPC?;SYST:PRES')

    def run_continously(self) -> None:
        """
        Set the instrument in run continously mode
        """
        self.write('INIT:CONT:ALL')

    def run_N_times(self, N: int) -> None:
        """
        Run N sweeps and then hold. We wait for a response before returning
        """

        st = self.sweep_time.get_latest()
        old_timeout = self.visa_handle.timeout

        if N not in range(1, 1000):
            raise ValueError('Can not run {} times.'.format(N) +
                             ' please select a number from 1-999.')

        # set a longer timeout, to not timeout during the sweep
        new_timeout = 1000*st*N + 1000
        self.visa_handle.timeout = new_timeout

        log.debug('Making {} blocking sweeps.'.format(N) +
                  ' Setting VISA timeout to {} s.'.format(new_timeout/1000))

        self.ask('*OPC?;NUMG{}'.format(N))

        self.visa_handle.timeout = old_timeout

    def invalidate_trace(self, cmd: str,
                         value: Union[float, int, str]) -> None:
        """
        Wrapper for set_cmds that make the trace not ready
        """
        self._traceready = False
        self.write(cmd.format(value))

    def startup(self) -> None:
        self._traceready = False
        self.display_format(self.display_format())

    def _s_parameter_setter(self, param: str) -> None:
        """
        set_cmd for the s_parameter parameter
        """
        if param not in ['S11', 'S12', 'S21', 'S22']:
            raise ValueError('Cannot set s-parameter to {}')

        # the trace labels changes
        self._traceready = False

        self.write('CALC:PAR:DEF{}')

    def _s_parameter_getter(self) -> str:
        """
        get_cmd for the s_parameter parameter
        """
        for cmd in ['S11?', 'S12?', 'S21?', 'S22?']:
            resp = self.ask('CALC:PAR:DEF?')
            if resp in ['1', '1\n']:
                break

        return cmd.replace('?', '')

    def _display_format_setter(self, fmt: str) -> None:
        """
        set_cmd for the display_format parameter
        """
        val_mapping = {'Log Mag': 'MLOG',
                       'Phase': 'PHAS',
                       'Group Delay': 'GDEL',
                       'Smith': 'SMIT',
                       'Polar': 'POL',
                       'Lin Mag': 'MLIN',
                       'Real': 'REAL',
                       'Imag': 'IMAG',
                       'SWR': 'SWR'}

        if fmt not in val_mapping.keys():
            raise ValueError('Cannot set display_format to {}.'.format(fmt))

        self._traceready = False
        self.write('CALC:FORM{}')

    def _display_format_getter(self) -> str:
        """
        get_cmd for the display_format parameter
        """
        val_mapping = {'MLOG': 'Log Mag',
                       'PHAS': 'Phase',
                       'GDEL': 'Group Delay',
                       'SMIT': 'Smith',
                       'POL': 'Polar',
                       'MLIN': 'Lin Mag',
                       'REAL': 'Real',
                       'IMAG': 'Imag',
                       'SWR': 'SWR'}

        # keep asking until we find the currently used format
        for cmd in val_mapping.keys():
            resp = self.ask('CALC:FORM?'.format(cmd))
            if resp in ['1', '1\n']:
                break

        return val_mapping[cmd]


Not sure where I am making mistakes. 
Sorry, this has been really long comment.

**Comment by jenshnielsen** [comment]
You are using the old qcodes measurement where the import has changed. I just fixed the hp notebook so it can run

I would suggest that you worry about getting the driver working first. 

Then you should read this notebook https://qcodes.github.io/Qcodes/examples/DataSet/Performing-measurements-using-qcodes-parameters-and-dataset.html to understand how to do the measurements 


Could you make a pull request against https://github.com/qcodes/qcodes_contrib_drivers with your new driver so we can look at it in a better interface

**Comment by Saba-Mehshar** [comment]
Hi @jenshnielsen 

I have pulled a new request against https://github.com/qcodes/qcodes_contrib_drivers .
Thank you very much for your consistent assistance.

**Comment by jenshnielsen** [comment]
This has moved to the contrib driver pr https://github.com/QCoDeS/Qcodes_contrib_drivers/pull/78 and seems to be more of a question of how to develop a driver than an error so closing this one
