### ISSUE TITLE
Aborting measurement fails

### ISSUE THREAD

**Issue by MerlinSmiles** [QCoDeS/Qcodes#224]
### Steps to reproduce
1. start a long running measurement
2. Plot the data
3. Hit abort button
### Expected behaviour

Measurement should stop
### Actual behaviour

measurement continues, the notebook is unusable, even a print() does not work
I had QtPlot enabled, not sure if that matters, which stops plotting

I see this very often, only resolution is to restart the notebook
### System

**operating system**
Win 7
**qcodes branch**
master, Merlins instrument, array_id

**Comment by giulioungaretti** [comment]
see #598 .
