### ISSUE TITLE
feature: Instrument communication log

### ISSUE THREAD

**Issue by alexcjohnson** [QCoDeS/Qcodes#229]
Make a "comm log" that can record all communication to/from an instrument, something like:

```
>>> source.enable_log()
>>> source.amplitude.set(0.5)
>>> source.amplitude.get()
0.5
>>> print(source.comm_log)
-> SOUR:VOLT:AMPL 0.500
-> SOUR:VOLT:AMPL?
<- 0.500
>>> souce.disable_log()  # done debugging, drop the overhead of keeping this stuff
```

I've added `->` and `<-` to the written and read strings respectively to differentiate them.
Also add timestamps to each message.

As discussed in #145 
cc @spauka @AdriaanRol

**Comment by jenshnielsen** [comment]
handled via logging module
