### ISSUE TITLE
Error to connect keithly2400 with RS232

### ISSUE THREAD

**Issue by sofomryu** [QCoDeS/Qcodes#2407]
If you encounter a bug use the following template.
If you have a feature request feel free to freestyle.
### Steps to reproduce
1.
![qcodes error rs232](https://user-images.githubusercontent.com/69798848/98387364-963dbb80-2051-11eb-9050-6d707e88479b.PNG)

2.
3.

### Expected behaviour
Tell us what should happen
The connection should be well operated and it worked well before.

### Actual behaviour
Tell us what happens instead
Now when I try to connect them, it shows me 'module 'pyvisa.constants' has no attribute 'BufferOperation''
I set both RS232 and keithley2400 with 
Baud: Rate 9600
Data: Bits 8
Stop: Bits 1
Parity: None
Terminal: LF

And I checked it's working well when I type command via NI MAX. 
What should I consider to solve this problem?

### System
**operating system**
windows10 64bit
**qcodes branch**
0.19.0
**qcodes commit**

**Comment by jenshnielsen** [comment]
Please try upgrading to qcodes `0.19.2` You have an incopatible combination qcodes and pyvisa installed. QCoDeS 0.19.2 should have support for both pyvisa 1.10 and 1.11

**Comment by sofomryu** [comment]
> Please try upgrading to qcodes `0.19.2` You have an incopatible combination qcodes and pyvisa installed. QCoDeS 0.19.2 should have support for both pyvisa 1.10 and 1.11

Thanks a lot! now it's working.
