### ISSUE TITLE
Finalize instrument names convetions. 

### ISSUE THREAD

**Issue by giulioungaretti** [QCoDeS/Qcodes#247]
module path: instrument_drivers.vendor_name.nameonthefront :
class name: nameonthefront

f.e.x
path:  instrument_drivers.alazartech.ATS850
class name: ATS850

**Comment by jenshnielsen** [comment]
We have standardized on creating a generic class i.e. with x in the name and create thin subclasses for all relevant models with and specific code in the subclass
