### ISSUE TITLE
MatPlot bug

### ISSUE THREAD

**Issue by nataliejpg** [QCoDeS/Qcodes#257]
### Steps to reproduce
1. Do a Loop over a parameter (with not many steps)
   eg `data1 = qc.Loop(v1.power[1,5,1]).each(v1.trace())`
2. Plot data using MatPlot
   eg `qc.MatPlot(data1.magnitude)`
### Expected behaviour

Hence I expect a measurements at power = 1,2,3,4 (although I also think it's worth a discussion over whether this is a bit misleading and it should include 5 but I realise that's a deliberate data acquisition decision). The plot should reflect this and have each measurement 'sweep/point' centred on the corresponding power at which it was measured. 
### Actual behaviour

Data acquisition is fine and plots fine in QtPlot but MatPlot shifts the data so that the centre of my power=1 data is at 1.5 etc and then my power=4 data is thrown away. In other words the plot shows data from power = 1-4 but am actually plotting data from 1=3 and shifting it all up by half so on the power axis what is shown between 1 and 2 is my data from my measurment at power=1 and so on.

Here's my actual case: 
![capture](https://cloud.githubusercontent.com/assets/4841569/16709026/04c08c58-4605-11e6-9106-a8e5ae981669.PNG)
### System

T5 Windows (sorry haven't checked version)

ZNB20_2 branch (merged master 8th July morning)

**Comment by giulioungaretti** [comment]
@jenshnielsen we did not fix this, right ?

Not sure it's a bug, rather a design flaw :P
