### ISSUE TITLE
multidimensional parameter units

### ISSUE THREAD

**Issue by nataliejpg** [QCoDeS/Qcodes#258]
This is another issue I noticed when doing the same thing as in [#257](https://github.com/qdev-dk/Qcodes/issues/257)
### Steps to reproduce
1. do a plot of a non standard parameter (in my case the FrequencySweep parameter when using rohde schwarz ZNB20 driver)
### Expected behaviour

units should show up on the graph if you have specified them in the parameter
### Actual behaviour

no units :( check out [#257](https://github.com/qdev-dk/Qcodes/issues/257) for picture.
### System

Windows 
ZNB20_2

**Comment by giulioungaretti** [comment]
@jenshnielsen  I think we fixed this ?

**Comment by jenshnielsen** [comment]
Yes indeed. We might need to add the correct units to the ZNB20 driver but support is there in the multi parameter
