### ISSUE TITLE
PyQtgraph live plot does not update 

### ISSUE THREAD

**Issue by AdriaanRol** [QCoDeS/Qcodes#259]
Issue made to get rid of the hack in PR #250 . 
### Steps to reproduce
1. Run Tutorial notebook from #250 

``` python
data = qc.Loop(c0.sweep(-20,20,0.1), delay=0.003).each(meter.amplitude).run(name='testsweep')
plotQ = qc.QtPlot()
plotQ.add(data.meter_amplitude)
```
### Expected behaviour

Expect to see a live updating plot of the data 
### Actual behaviour

Plots only what is in "data" the moment the plot function is called. 
### Workaround

``` python
while data.sync():
    plotQ.update()
plotQ.update()
```

The following code will keep updating the plot (in the main thread) while the data taking is not finished yet. 
### System

**operating system**
OS X El Capitan 10.11.5 (15F34)
**qcodes branch**
"examples" (only contains notebook so should be close to master) 
**qcodes commit**
Commit: 007e5f95ac5

**Comment by giulioungaretti** [comment]
Closing. MP is deprecated. And eventually the new architecture will solve this things.
