### ISSUE TITLE
Essentials list V0.1

### ISSUE THREAD

**Issue by guenp** [QCoDeS/Qcodes#265]
# Essentials for initial release August 2016

Some of these may be mentioned in issues related to this milestone.
Make sure all these boxes are checked. If they are, we're ready for release! 🍻
## Documentation
- [x] Getting Started guide x 
- [x] API docs x
- [x] Style guide x 
## Data
- [x] Binary data storage format (e.g. HDF5) 
- [ ] Explicit use cases + format
  - [ ] Array ID names
- [ ] Support for "complex" measurements (not using a Loop)
  - [ ] Modular use outside of a Loop 
- [ ] Multi-value parameters
  - [ ] Tuple
  - [ ] Array
- [ ] Access from main process to datasets
## Parallelism
- [ ] "Foreground" fully functional with live plot x 
  - [ ] No multiprocessing as default, keep in the code as "experimental" x
- [ ] Logging + debugging to file x 
## Plotting
- [ ] Live plotting x 
## Instruments x
- [ ] Handling of massively asynchronous instruments (for example using concurrent.futures interface). x 
- [ ] Channels
- [ ] Syntax:

``` python
instruments.channel_list[0].volt
voltages = [0,1,2,1,0]
instrument.channel_list.volt(voltages)
```

``` python
instruments.channel_list[0].set_async(0)
instruments.channel_list[1].set_async(1)
instruments.channel_list.do_things()
```
## Syntax
- [x] Loop(Combine(p1,p2)[(x0,y0),(x1,y1),..]).each(..).run(..) x
- [x] qc.Measure(vna.s11, vna.s21).setup(..).teardown(..).run(..) and Loop(..).setup(..).teardown(..).run(..) x

**Comment by WilliamHPNielsen** [comment]
We've changed directions so many times since this plan was aired, so I am closing this issue.
