### ISSUE TITLE
station.snapshot_base doesn't respect parameter.snapshot_exclude

### ISSUE THREAD

**Issue by mgunyho** [QCoDeS/Qcodes#2671]
I noticed the following behavior when directly adding parameters to a station:

```py
from qcodes import Station, Parameter

station = Station()

station.add_component(Parameter("foo", snapshot_exclude=True))

station.snapshot_base()
```
This issues a warning "foo is used in the snapshot while it should be excluded from the snapshot", and the parameter indeed appears in the snapshot even though it shouldn't.

This is a simple fix, it should just be a an additional condition [here](https://github.com/QCoDeS/Qcodes/blob/85f56f312ad1d784de72a1b816022d5a1650803c/qcodes/station.py#L184). I don't have time to write a proper PR with tests for this right now, but I can submit something later if this isn't fixed by then.

**Comment by astafan8** [comment]
thank you @mgunyho ! a PR later is great :)
