### ISSUE TITLE
Plotting discrepancy between plot_dataset and plottr

### ISSUE THREAD

**Issue by MdKquantum** [QCoDeS/Qcodes#2917]
I think I might have found a bug or strange feature in plot_dataset or plottr. I have been performing simple 2D current sweeps, in which I measure the current on a sample versus two different voltages. 

I noticed that the axis of plotting are switched while comparing the plottr result to plot_dataset, even if I use set_shapes to fix the  shape of the dataset. In the plot_dataset case the fast axis is along y, while in plottr this fast axis is along x.

### Example code of a 2D current sweep

`

    meas = Measurement(exp=exp_name,station = station)

    meas.register_parameter(DAC.ch1.volt)
    meas.register_parameter(DAC.ch3.volt)
    meas.register_parameter(DAQ.ai0.current, setpoints = (DAC.ch1.volt,DAC.ch3.volt))

    meas.set_shapes(detect_shape_of_measurement((DAQ.ai0.current),(steps1,steps2))

    with meas.run as datasaver():
        for set_v1 in np.linspace(start_val1,stop_val1,steps1):
            DAC.ch1.volt.set(set_v1)
        
            time.sleep(settletime1)
            for set_v2 in np.linspace(start_val2,stop_val2,steps2):
                DAC.ch3.volt.set(set_v2)
            
                time.sleep(settletime2)
                data = DAQ.ai0.current.get()
            
                datasaver.add_result((DAC.ch1.volt,set_v1),
                                      (DAC.ch3.volt,set_v2),
                                      (DAQ.ai0.current,data))
                                
    plot_dataset(datasaver.dataset)
`

### Expected behaviour
I Would expect the two plotting instances to show the plot in a similar way.

### Actual behaviour
The axis of plottr are switched compared to the qcodes function plot_dataset

Thank you for any help. In case I should also put this question on the plottr github please let me know.

**Comment by jenshnielsen** [comment]
It is somewhat arbitrary which axis of a 2d plot that you chose to be the x and the y axis. Plottr has chosen a different convention from qcodes by default but please note that plottr supports changing the axis so you can relatively easily change the plot in plottr to match the one from qcodes

**Comment by MdKquantum** [comment]
Hmm, that point about switching the axis is true. However I've also seen, that after I switched the axis in plottr during the live measurement, the complete dataset was transposed and then stored in the db. Which made plot_dataset also switch axis and the result would still be opposite from what I see in plottr. This was before I found out about set_shapes, I can run a few tests later this afternoon to check if this behaviour still exists with set_shapes in my measurement setup.

**Comment by jenshnielsen** [comment]
I am not sure I understand what you mean. There should be no transposing of the complete dataset in qcodes.

 If the plot is transposed in plottr while liveplotting after you manually changed the axis that sounds like a bug in plottr and should be raised there.
