### ISSUE TITLE
Station should be able to load multiple yaml files

### ISSUE THREAD

**Issue by guenp** [QCoDeS/Qcodes#2924]
Currently, `Station.load_config_file` can only load a single YAML file. Even when running said method a second time on a different yaml file, it does not append the data from the new file and keeps the original yaml file in memory. For systems with many instruments and parameters it would be very useful if instead of a single file, `Station.load_config_file` would be able to load multiple yaml files and combine them.

Example usage as proposed by @samantha-ho:

```python
station.load_config_file([foo.yaml, bar.yaml, baz.yaml])
```

CC @jenshnielsen, as discussed in our meeting last week.

**Comment by FarBo** [comment]
@guenp 
Thank you for openning this issue.
We will add the suggested feature to qcodes :)
