### ISSUE TITLE
qcodes does not work with qt5

### ISSUE THREAD

**Issue by peendebak** [QCoDeS/Qcodes#317]
Possible solution is to use [qtpy](https://github.com/spyder-ide/qtpy) as a wrapper for both qt5, qt4 and pyside.

@giulioungaretti

**Comment by giulioungaretti** [comment]
@peendebak @eendebakpt  actually it does !

**Comment by peendebak** [comment]
@giulioungaretti Current master branch indeed works. It does not yet work with #290

**Comment by giulioungaretti** [comment]
@peendebak #290 also works with qt5 now :D  since https://github.com/QCoDeS/Qcodes/pull/290/commits/acb856b538d41cbe947a73ccd2f389c5f57ffd51 !
