### ISSUE TITLE
Overwriting parameters in inherited instruments

### ISSUE THREAD

**Issue by AdriaanRol** [QCoDeS/Qcodes#32]
Currently parameters are added to an instrument in the **init**. Once a parameter is added it is not possible to overwrite this by using another add_parameter command. When inheriting an instrument you generally want to overwrite inherited functions as well as some parameters. This is currently not possible. 

The current workaround would be to overwrite the entire **init** and copy paste all the add_parameter commands that were in the parent class. I think it makes sens to run super().**init**(...) and then only overwrite those parameters that are overwritten.

**Comment by giulioungaretti** [comment]
@AdriaanRol  how about implementing as you proposed an add_praemter(...., overwrite=False) ?

**Comment by jenshnielsen** [comment]
This is now possible via #3125
