### ISSUE TITLE
Auto saving plots.

### ISSUE THREAD

**Issue by giulioungaretti** [QCoDeS/Qcodes#376]
Some people in qdev would like to have this feature, so that they can immediately spot the data they are searching for.
Related to #158, but different because does not require extra stuff.
Not sure which approach I like the best for now.

**Comment by AdriaanRol** [comment]
@giulioungaretti , The location_formatter I use saves datafiles all in their own folder (named with their timestamp). I think it makes sense to save a default plot (by default) in the location next to the corresponding dataset. This makes it very easy to browse around the data and quickly look at analyzed files. 

To clarify. 
I suggest, give a default location to the saveplot method that is next to the dataset.
