### ISSUE TITLE
Incorrect baud rate in QDevil QDAC drivers

### ISSUE THREAD

**Issue by pharveycollard** [QCoDeS/Qcodes#3930]
Our colleagues and I from the IBM Research Europe - Zurich lab have found the baud rate in QDevid QDAC drivers to be incorrect.

### Steps to reproduce
1. In the file "qcodes/instrument_drivers/QDev/QDac_channels.py", at line 200, the `handle.baud_rate = 480600` is incorrect.
2. In the file "qcodes/instrument_drivers/QDevil/QDevil_QDAC.py", at line 240, the `handle.baud_rate = 480600` is incorrect.

### Expected behaviour
From our QDAC manual sheet 14(51), we can read 

> [...] select a baud rate of 460800 [...]

### Actual behaviour
The numbers 6 and 8 are inverted. We don't see errors often due to this, but it should be corrected nevertheless.

If you are using a released version of qcodes (recommended):
**qcodes version**: 0.32

**Comment by astafan8** [comment]
@pharveycollard thank you for reporting! Could you check #3931 ?

**Comment by pharveycollard** [comment]
Thanks!
