### ISSUE TITLE
SignalHound_USB_SA124B  print statement.

### ISSUE THREAD

**Issue by giulioungaretti** [QCoDeS/Qcodes#415]
@elrama- @AdriaanRol 

The print statement in this driver are pretty interesting!
Is there any reason for https://github.com/QCoDeS/Qcodes/blob/master/qcodes/instrument_drivers/signal_hound/USB_SA124B.py#L271 ? 

I am thinking of replacing  the three print statement with a single log.error with a multi line string!

**Comment by AdriaanRol** [comment]
@giulioungaretti I agree on using logging for these things. My preference would be logging.warning but my guess is you want to build in some logging module for QCoDeS? 

In any case @elrama- is on holidays now so I don't expect him to react, but I do remember that he spent some time on these error messages as it took some time to figure out how the driver worked. 

Good to see driver improvements happening 👍

**Comment by giulioungaretti** [comment]
@AdriaanRol  https://github.com/QCoDeS/Qcodes/pull/416/files#diff-227f5982ce997835113c6c7997170267R271 is my proposal :D 
If you raise after, it should be an logging.error rather than a warning but that it's more of a decision the driver artist has to make. 


Yes you guessed right :D !
