### ISSUE TITLE
refactor Parameter out of Instrument

### ISSUE THREAD

**Issue by alexcjohnson** [QCoDeS/Qcodes#42]
from @AdriaanRol discussion in #38 

> I noticed that the parameter class is located inside the instrument folder. Previously this made sense but I think that in recent PRs #39 and #40 we have made the notion of a parameter more abstract and indepenent of the instrument. Would it make sense to separate/refactor this?

Yes, yes it would make sense

**Comment by giulioungaretti** [comment]
Possibly to be fixed in. #403 !
