### ISSUE TITLE
Missing Keithley model

### ISSUE THREAD

**Issue by amitjansc** [QCoDeS/Qcodes#4287]
Hi,

The model `2634B` is missing inside the `Keithley_2600` class:

https://github.com/QCoDeS/Qcodes/blob/3acdc3153dc8b47367a0c8dfbb8622aea5b7255b/qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py#L720

**Comment by jenshnielsen** [comment]
Thanks for spotting this @amitjansc Are you willing to make a pull requrest to fix this?

**Comment by amitjansc** [comment]
Yes! Please find the PR [here](https://github.com/QCoDeS/Qcodes/pull/4290).

**Comment by jenshnielsen** [comment]
closed by #4290
