### ISSUE TITLE
hdf5 formatter does not implement proper interface for write_metadata

### ISSUE THREAD

**Issue by peendebak** [QCoDeS/Qcodes#440]
The `write_metadata` function has an argument `read_first`:

https://github.com/QCoDeS/Qcodes/blob/master/qcodes/data/format.py#L107

The HDF5 formatter does not have this argument:

https://github.com/QCoDeS/Qcodes/blob/master/qcodes/data/hdf5_format.py#L238

This generates an error here: 

https://github.com/QCoDeS/Qcodes/blob/master/qcodes/data/data_set.py#L764

A one line fix would be to add the `read_first` argument to the hdf5 formatter, but ignore it.

@giulioungaretti @AdriaanRol

**Comment by AdriaanRol** [comment]
@peendebak , I thought I took care to preserve the interface when making the hdf5 formatter. Maybe this got added later? (or maybe I just messed up). I approve of your immediate solution.
