### ISSUE TITLE
Get_idn fails for AMI430 3D instrument

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#4590]
the Instrument class implements get_idn by calling ask but that will in general not work on virtual instruments such as the AMI4303D but raise an exception that is handled and logged. 

Virtual instruments should either override get_idn to not fail and respond with something useful or we should rework this so get_idn is not implemented like this for the generic class

**Comment by astafan8** [comment]
opened #4611 for the generic issue about all virtual instruments
