### ISSUE TITLE
Keithely 2600 "resolution"

### ISSUE THREAD

**Issue by giulioungaretti** [QCoDeS/Qcodes#467]
@MerlinSmiles  right now  we are limiting the set to 8 digits (https://github.com/QCoDeS/Qcodes/blob/master/qcodes/instrument_drivers/tektronix/Keithley_2600.py#L23)
Afaik it can go to to 12 digits. Do you confirm ?

**Comment by MerlinSmiles** [comment]
@giulioungaretti no hardware around in this train, try it out? stupid mistake if it can go to 12 digits.

**Comment by giulioungaretti** [comment]
@MerlinSmiles it seems to go that low on the 2614B.

I am not 100% sure but the manual reports:

| Range  | Programming Resolution | Accuracy (1 Year), 23°C ±5°C ±(% rdg. + amps) | Typical Noise (peak-peak) 0.1Hz–10Hz |
|--------|------------------------|-----------------------------------------------|--------------------------------------|
| 100 nA | 2 pA                   | 0.06% + 100 pA                                | 5 pA                                 |

**Comment by giulioungaretti** [comment]
@MerlinSmiles  

![sketch 1](https://cloud.githubusercontent.com/assets/2694199/22370878/0eedc604-e494-11e6-9317-f1fe039678a8.png)

**Comment by giulioungaretti** [comment]
Let me know if you agree with the way I read the manual 📄

**Comment by MerlinSmiles** [comment]
@giulioungaretti looks very reasonable. Could you check if you can send 12 digits when in >1A range? And also how many digits do you get back when reading?
