### ISSUE TITLE
dond, do1d ... functions don't return data after Interrupt

### ISSUE THREAD

**Issue by grothe6** [QCoDeS/Qcodes#4800]
In the do*d functions, after a KeyboardInterrupt or a BreakConditionInterrupt, the raised exception gets re-raised in the [_handle_plotting function](https://github.com/QCoDeS/Qcodes/blob/2346131825b0302c6203b62fca56b958cdc725f0/qcodes/dataset/dond/do_nd_utils.py#L105):

```python
if interrupted:
    raise interrupted

return res
```

As a consequence, the data is not returned.

While this may be desired for KeyboardInterrupt, for a BreakConditionInterrupt it should not. Although I think, it doesn't harm to return the data even after a KeyboardInterrupt.

My proposal would be to return the data either way or only after a BreakConditionInterrupt.

**Comment by jenshnielsen** [comment]
Sounds reasonable to me. I would probably suggest that we simply log with a warning that the measurement has been interrupted and the data may be incomplete and then return it. @grothe6 Do you fell like making a pr with that change?
