### ISSUE TITLE
Update Sphinx favicon config

### ISSUE THREAD

**Issue by tcmetzger** [QCoDeS/Qcodes#5045]
Thanks for using [Sphinx Favicon](https://github.com/tcmetzger/sphinx-favicon) in your project! I just released version 1.0 of the extension, which brings one breaking change: to better conform with Python standards, we changed the module name to `sphinx_favicon` (instead of `sphinx-favicon`). This means you'll have to update the name in the `extensions` list of your conf.py file (https://github.com/QCoDeS/Qcodes/blob/master/docs/conf.py#L81) to use version 1.0. Otherwise, your existing configuration should continue to work!

**Comment by jenshnielsen** [comment]
@tcmetzger Thanks will be fixed via #5046
