### ISSUE TITLE
Captured_run_id is incorrect if run has been inserted

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#5328]
Currently a new run gets a captured_run_id inserted based on the following logic

```
    if captured_run_id is None:
        with atomic(conn) as conn:
            query = """
            SELECT
                max(captured_run_id)
            FROM
                runs"""
            curr = transaction(conn, query)
            existing_captured_run_id = one(curr, 0)
        if existing_captured_run_id is not None:
            captured_run_id = existing_captured_run_id + 1
        else:
            captured_run_id = 1
```

Consider a database with 10 runs where a dataset is added via ds = load_from_netcdf(...) and ds.write_metadata_to_db() 
If that dataset has captured_run_id==100 the next dataset created as part of a measurement would have
run_id ==12 and captured_run_id==101 breaking the expectation that the run_id == captured_run_id for any new dataset. 

Suggested fix replace max(captured_run_id) with max(run_id) in the above code and check once the row has been written that run_id == captured_run_id for new  runs.

**Comment by astafan8** [comment]
> Suggested fix replace max(captured_run_id) with max(run_id) in the above code

oh totally! Good catch!
