### ISSUE TITLE
AWG 5014 ref clock bad parameter name /confusion 

### ISSUE THREAD

**Issue by AdriaanRol** [QCoDeS/Qcodes#537]
The AWG 5014 driver has two distinct "parameters" in the hardware, 
- Clock source -> int or ext 
- Reference oscillator -> int or ext
![image](https://cloud.githubusercontent.com/assets/6142932/24244655/209c178c-0fc0-11e7-8f63-8ca102bf1acf.png)

The recently updated 5014 driver introduces a 'parameter' ref_clock_source. 
https://github.com/QCoDeS/Qcodes/blob/master/qcodes/instrument_drivers/tektronix/AWG5014.py#L160
This refers to using an internal or external clock and and has nothing to do with the reference oscillator, making this a confusing name. 
Additionally there is no parameter that sets the reference oscillator. 

The driver does contain some reference to these parameter under their proper name. 
https://github.com/QCoDeS/Qcodes/blob/master/qcodes/instrument_drivers/tektronix/AWG5014.py#L847-L852

I would suggest the following fix. 
- Rename the `ref_clock_source` parameter to `clock_source`. 
- Add a parameter for the `reference_source`
 Both of these names are the names that the AWG uses internally, both in it's GUI as in it's sequencer config. 

@WilliamHPNielsen as author of the recent fix, do you agree with these changes? If so I will be sending a PR shortly.

**Comment by nataliejpg** [comment]
totally agree with @AdriaanRol, have been meaning to flag this up but got distracted/waylaid. At the moment initialising the qcodes instrument seems to set the reference source to internal even if it the instrument previously was set to external but I hadn't dug into what the parameter was actually doing.

**Comment by AdriaanRol** [comment]
@nataliejpg have you seen #538 ?
