### ISSUE TITLE
Units, 1e9 vs 1G vs 1000000000

### ISSUE THREAD

**Issue by AdriaanRol** [QCoDeS/Qcodes#56]
@alexcjohnson 
Yesterday we had a quite intense discussion in the lab on units. 
I am personally a big fan of using SI units for everything and then adding e9 (or e-9 or e6 etc) to it to convert it to whatever quantity we need. 
There are several pros and cons for this way of doing it 
Pros: 
- The same everywhere 
- Intuitive to remember/convert 

Cons: 
- type eX every time you set a value/range/linspace, everything! 
- hard to read when printed or output to terminal unless explicit formatter is specified 
### displaying problem

I looked a bit in the print problem but it looks like there is no easy solution to this. I found the following things which are related but don't cover it completely: [numpy set printoptions](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.set_printoptions.html), [converting to a custom float class](http://stackoverflow.com/questions/1566936/easy-pretty-printing-of-floats-in-python). 
I guess other alternatives (which I haven't found) would be , add a very short conversion function to "pretty float" for easy printing i.e. `print(pretty(x))`. 
Modify the base python float class **repr** (not possible as it is immutable and would require recompiling python) 
Note if we are going down the pretty float road we can also incorporate the G,M,k, , m, u, n prefixes. 
### Specifying input problem

I do not know the best way to address this one, from what I understood typing e9 every time is considered a pain. A valid alternative would be to use scientifix prefixes after typing the number i.e. `x=1.24G` would set x to 1.24e9.

**Comment by giulioungaretti** [comment]
Cosing as per #494 .
