### ISSUE TITLE
subplots do not work with MatPlot

### ISSUE THREAD

**Issue by eendebakpt** [QCoDeS/Qcodes#609]
A minimal example:
```
import qcodes
import qcodes.tests.data_mocks

ds=qcodes.tests.data_mocks.DataSet1D()
p = qcodes.MatPlot()
p.add(ds.default_parameter_array() )

p = qcodes.MatPlot(subplots=(2,2))
p.add(ds.default_parameter_array()) # fail
p.add(ds.default_parameter_array(), subplot=1) # fail
```

@giulioungaretti

**Comment by jenshnielsen** [comment]
This should be fixed by #610. @eendebakpt  would be great if you have the time to test that pr. This should only happen if you create 2d subplot grids. I would expect the code to function correctly for `subplots=(1,n)` or `subplots=(n,1)
