### ISSUE TITLE
Data structures 

### ISSUE THREAD

**Issue by AdriaanRol** [QCoDeS/Qcodes#62]
@alexcjohnson 
Hi Alex, I noticed you mentioned that one of the next steps will be to improve data saving so I thought I'd share my ideas on it before everything is made and fully integrated. One of the things I want to do after the data saving is move over our analysis and/or built a framework for easily analysing data. Automation of analysis of experiments is one of the things I have in mind when talking about data structures but is a subject that is large enough to warrant it's own discussion. 

With respect to data structures I think there are a few aspects that are relevant 
- Structure of data in the file 
- data format (JSON, HDF5, data-server or other)  
- file-handling and interfaces (default directories, search and load functions etc) 
### Structure of the data file

I like the current structure a lot, I think the way a dataset can be passed to a plot and contains all the metadata. However when doing analysis I find that I require some more functionality. 
To be specific, I require 
- A snapshot of the settings at the time of the experiment 
- The ability to store additional data in the file (fit-results, rotated and normalised data etc) 
- Other metadata (commit hash of our personal code, datatime etc) 

The way we address this currently is by having a hierarchical data structure that makes a distinction between a dataset (array's of values + labels) and the datafile (contains different groups of which the dataset is one). I would propose to use a similar hierarchical format for Qcodes. 
### Data format

We have had a lot of discussions on our side with respect to the data format. Currently JSON is the default and we (in Delft) are more used to HDF5, let me just summarise the pros and cons as I see them with the goal of making our use of both better. I guess as long as there is a good data handler the underlying backend does not really matter (similar to how we are with plotting now) but I guess the default will significantly impact how we think about it. 
@cdickel , I know you are pro HDF5 can you go over this and see if there is anything I missed/you want to add? 
- Pro JSON 
  - Simple/text based/openable in any editor 
  -  Native support for dictionaries (we use a workaround in HDF5) 
  -  current QCodes default 
- Pro H5PY/HDF5 
  -  HDF5 Hierarchical data-viewer (allows browsing datafile and folding of folders, looked around but did not find equivalent for JSON) 
  - File-sizes (this is a real problem when taking single shot data for long measurements) 
  - Possible to write/extend a dataset that is open, prevents data loss when experiment crashes 
  - Easily extract data in hierarchical fashion (no string parsing or custom import functions)
  - Can easily add new data groups to an existing file  
  - Delft default (admittedly only a pro for us) 
- Alternatives
  - If anyone knows of any alternatives please let me know 

I would be very willing to switch to JSON but to me it does not offer the same as HDF5 at this point. I would love to have some discussion on this. 
### Interface/file-handling

We currently use a format that saves any datafile as follows: `user_datadirectory/YYMMDD/HHMMSS_label/HHMMSS_label.hdf5`. The `user_directory` is a global variable that is set upon initialisation of the environment (similar to creating an instrument upon init). This directory typically does not change for several months. The label is a non-unique identifier for an experiment such as e.g. `T1_qubit_3`, we typically do the same run multiple times and do not want to worry about coming up with unique names, the timestamp ensures uniqueness. The file is nested in a folder with the same name to allow saving figures that come out of the analysis next to it. 

On the analysis side we have functions that look for data files in one of three ways. If a label is specified it looks for the last file that has that label, e.g. `T1` would find our `T1_qubit_3` file. If a timestamp is specified it uses this as a unique identifier for a file. If nothing is specified it will default to the last generated file. On top of that we have a whole bunch of higher level functions. 

This scheme is heavily qtlab inspired and works pretty well for us. Some of the drawbacks we have encountered are: 
- timestamp is not unique when doing very short experimental runs (sometimes multiple start within the same second) 
- Only possible to pick one user_datadirectory 

I'd be interested in what your ( @alexcjohnson )  plans are for this kind of interface and file/folder handling. I understand that you currently have to specify all this when using the Loop but I have to admit I have not used that in a while. 

@cdickel, Can you let me know what you think of all this? I tried to incorporate ideas from our discussions over the last year in it but I am sure I have missed some. 
@damazter , what do you think? You guys do things slightly different so I am curious.

**Comment by alan-geller** [comment]
@AdriaanRol @majacassidy @peendebak @guenp @damazter @cdickel 
Can we close this issue as subsumed under the new DataSet?

**Comment by WilliamHPNielsen** [comment]
@alan-geller let's do that.
