### ISSUE TITLE
notebook // matplotlib confusion 

### ISSUE THREAD

**Issue by giulioungaretti** [QCoDeS/Qcodes#624]
The function in_notebook  is pretty useless, and it  prevents MatPlot to be in the qcodes name space, for no good reasons.
We do not really depend on the notebook anymore (thankfully).

**Comment by peendebak** [comment]
@giulioungaretti Removing the notebook check fixes the issue, but it adds overhead in importing qcodes. For people wanting to quickly import qcodes (this will probably become important again when doing multiprocessing) the overhead of importing pyqtgraph and matplotlib is significant.

**Comment by giulioungaretti** [comment]
@eendebakpt @peendebak  then we can put a config switch ? see pr #625

**Comment by peendebak** [comment]
@giulioungaretti The config option in #625 looks good to me.

**Comment by astafan8** [comment]
I close it since the fix has been implemented in #625 and #699
