### ISSUE TITLE
QDAC driver crashes

### ISSUE THREAD

**Issue by alan-geller** [QCoDeS/Qcodes#658]
The QDAC firmware crashes sporadically if you send it VISA commands too quickly.

Relayed by Alan; David Sabonis can demonstrate and provide more specifics. Dave Wecker has run into this in Igor; the only solution he came up with is to add a delay to the driver.

**Comment by jenshnielsen** [comment]
I think this is only the case if you do not read back from the command and further more Rikke has improved the firmware to prevent this
