### ISSUE TITLE
driver/Tektronix TPS2012 oscilloscope - Issues with driver

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#666]
@WilliamHPNielsen wrote in #642 about calc_set_points

There are some conditions under which this call does not return the full expected response. We should ensure that these conditions are not met. (Sorry, I don't remember the details, but it's something like an enabling of the channels)

**Comment by WilliamHPNielsen** [comment]
I think it might be the following condition: is the channel enabled?

**Comment by WilliamHPNielsen** [comment]
Yup, this is even written as a comment in the driver.
