### ISSUE TITLE
Change QCoDeS plot axis labels from V to mV

### ISSUE THREAD

**Issue by jhenshaw** [QCoDeS/Qcodes#668]
If you encounter a bug use the following template.
If you have a feature request feel free to freestyle.
### Steps to reproduce
1. Plot something that generates an axis with 4-decimial place accuracy
2. Note that it is labeled as "0.000X" Volts (for example)

### Expected behaviour
We should simplify the axis labels to be in Mv, thus jettisoning the extra digits and de-cluttering the plot.  This should be done only (obviously) where our precision begins 3 digits out. Stick with Volts where it makes sense.

### Actual behaviour
Axis is labeled as "0.000X" Volts (for example)instead.
Samples are attached.

### System
Any

Master branch
![capture](https://user-images.githubusercontent.com/10354681/28189602-70f1079c-67db-11e7-9710-a63b76b0fa87.PNG)

**qcodes commit**

**Comment by jenshnielsen** [comment]
fixed for qdev specific version in https://github.com/qdev-dk/Qcodes/pull/60

**Comment by jenshnielsen** [comment]
Still need to fix the colorbar which may also have volts on the scale
