### ISSUE TITLE
Keysight Infiniium S series scope drivers

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#701]
We need drivers 
For the new blue force fridges
* MSOS254A http://www.keysight.com/en/pdx-x202069-pn-DSOS254A/high-definition-oscilloscope-25-ghz-4-analog-channels?nid=-32531.1150280&cc=DK&lc=dan
To aid the development of the mDAC  
* MSOS104A http://www.keysight.com/en/pdx-x202068-pn-DSOS104A/high-definition-oscilloscope-1-ghz-4-analog-channels?nid=-32531.1150279&cc=DK&lc=dan

**Comment by Dominik-Vogel** [comment]
I'll be working on the MSO104A.

**Comment by Dominik-Vogel** [comment]
The driver has been implemented in PR#766
