### ISSUE TITLE
Driver: Yokogawa GS210

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#705]
I don't find that model online:

Could be the GS200 or the GS610 perhaps
http://tmi.yokogawa.com/vn/products/generators-sources/source-measure-units/

We have a very minimal driver for the GS200 in https://github.com/QCoDeS/Qcodes/blob/master/qcodes/instrument_drivers/yokogawa/GS200.py

**Comment by jenshnielsen** [comment]
More information from John Watson
```
The GS210 is just the GS200 with the option of having the output terminals on the front of the instrument (Yokogawa’s documentation is kind of confusing on this), so the GS200 driver is the correct one for what we are buying.  I took a quick look at the driver, and I think it will need to be extended a bit to allow the types of measurements we typically would use it for (it looks like it currently just initializes communication with the instrument).```

**Comment by spauka** [comment]
Coincidentally I've been working on this driver at the same time.

See:
https://github.com/spauka/Qcodes/blob/device-dev/qcodes/instrument_drivers/yokogawa/GS200.py

It will be ready for a pull request soon...

**Comment by jenshnielsen** [comment]
@spauka Great and thanks for the heads up

**Comment by sohailc** [comment]
This issue belong on the StationQ repo: https://github.com/QCoDeS/StationQ/issues/16
