### ISSUE TITLE
Issue with monitor using qdac with channels 

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#708]
The new channels in the QDac does not render well using the monitor https://github.com/qdev-dk/Qcodes/blob/master/qcodes/monitor/monitor.py because each channel is rendered as an individual instrument. 

@giulioungaretti Is the eml source code for the monitor in qcodes/monitor/dist/ available somewhere

**Comment by giulioungaretti** [comment]
https://github.com/QCoDeS/GUI

**Comment by jenshnielsen** [comment]
Thanks, turns out that a fix to the dict from the python side is sufficient
