### ISSUE TITLE
Software trigger routine for keysight 34465A and Keithley sourcemeter

### ISSUE THREAD

**Issue by majoqubitT10** [QCoDeS/Qcodes#720]
It would be very useful to have software triggered readings into data buffer for the dmm and sourcemeters similar to how that is done for the SR830 as an alternative to the sync/timed readout already implemented

**Comment by WilliamHPNielsen** [comment]
Okay, I'll give it a look.

**Comment by WilliamHPNielsen** [comment]
The Keysight does not gain any speed upon being software triggered. See #729.

**Comment by WilliamHPNielsen** [comment]
The Keithley can be made twice as fast (assuming some mode of operation). See #747.
