### ISSUE TITLE
No Async data retrieval

### ISSUE THREAD

**Issue by MerlinSmiles** [QCoDeS/Qcodes#73]
@alexcjohnson I am using the #70 Inst Process branch with real instruments (#53).
This works fine so far, all that talking works, but not async.

I am using a super simple dmm, you can:
- Read a value (This starts a measurement in the instrument, and then returns the value (and blocks while doing so))
- Init a measurement (non-blocking) and ask for the data(blocking, but fast) later

The second approach is what i'm used to do for async stuff, Tell all instruments that I want information and then ask for it later.

I add a parameter like this:

``` python
self.add_parameter('volt',
                   get_cmd='READ?',
                   get_parser=float)
```

I tried timing a few things here:

``` python
# create Instruments
k1 = keith.Keithley_2600('Keithley1', 'GPIB0::15::INSTR',channel='a')
k2 = keith.Keithley_2600('Keithley2', 'GPIB0::15::INSTR',channel='b')

a1 = agi.Agilent_34400A('Agilent1', 'GPIB0::11::INSTR')
a2 = agi.Agilent_34400A('Agilent2', 'GPIB0::6::INSTR')

# set integration time (number of line cycles)
a1.NPLC.set(10)
a2.NPLC.set(10)
```

``` python
station1 = qc.Station(a1,a2)
station1.set_measurement(a1.volt)
station2 = qc.Station(a1,a2)
station2.set_measurement(a1.volt, a2.volt)
```

``` python
# Time single readings
with Timer('Time s1'):
    station1.measure()
with Timer('Time s2'):
    station2.measure()
```

```
[Time s1]
Elapsed: 0.41602373123168945
[Time s2]
Elapsed: 0.8230471611022949
```

``` python
# Time single readings
with Timer('Time a1'):
    a1.volt.get()
with Timer('Time a2'):
    a2.volt.get()
```

```
[Time a1]
Elapsed: 0.4150238037109375
[Time a2]
Elapsed: 0.4080233573913574
```

``` python
with Timer('Time Loop 1'):
    data = qc.Loop(k1.volt[-5:5:1], 0).each(a1.volt).run(location='testsweep', overwrite=True,background=False)

with Timer('Time Loop 2'):
    data = qc.Loop(k1.volt[-5:5:1], 0).each(a1.volt, a2.volt).run(location='testsweep', overwrite=True,background=False)
```

```
DataSet: DataMode.PUSH_TO_SERVER, location='testsweep'
   volt: volt
   volt_set: volt
started at 2016-04-15 16:35:52
[Time Loop 1]
Elapsed: 4.65026593208313
DataSet: DataMode.PUSH_TO_SERVER, location='testsweep'
   volt_1: volt
   volt_0: volt
   volt_set: volt
started at 2016-04-15 16:36:00
[Time Loop 2]
Elapsed: 8.254472017288208
```

``` python
with Timer('Time Loop 1'):
    data = qc.Loop(k1.volt[-5:5:1], 0).each(a1.volt).run(location='testsweep', overwrite=True)
    while data.sync():
        time.sleep(0.1)
```

```
DataSet: DataMode.PULL_FROM_SERVER, location='testsweep'
   volt: volt
   volt_set: volt
started at 2016-04-15 16:36:03
[Time Loop 1]
Elapsed: 4.743271112442017
```

``` python
with Timer('Time Loop 2'):
    data = qc.Loop(k1.volt[-5:5:1], 0).each(a1.volt, a2.volt).run(location='testsweep', overwrite=True)
    while data.sync():
        time.sleep(0.1)
```

```
DataSet: DataMode.PULL_FROM_SERVER, location='testsweep'
   volt_1: volt
   volt_0: volt
   volt_set: volt
started at 2016-04-15 16:36:16
[Time Loop 2]
Elapsed: 8.797503232955933
```

apart from the negative delay warnings #58 I now get flooded by additional Measurement timestamps(?)
`[16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement] [16:36:18.811 Measurement ERR] WARNING:root:negative delay -0.000027 sec
[16:36:19.643 Measurement ERR] WARNING:root:negative delay -0.000024 sec
[16:36:20.470 Measurement ERR] WARNING:root:negative delay -0.000027 sec`

**Comment by giulioungaretti** [comment]
@MerlinSmiles should this issue be closed now  ?

**Comment by MerlinSmiles** [comment]
Not really, unless reopening a new issue that relates to the current
version where we don't have async stuff either.

On May 7, 2017 17:17, "Giulio Ungaretti" <notifications@github.com> wrote:

@MerlinSmiles <https://github.com/MerlinSmiles> should this issue be closed
now ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/QCoDeS/Qcodes/issues/73#issuecomment-299713023>, or mute
the thread

**Comment by giulioungaretti** [comment]
@MerlinSmiles  but issue here was that using the server thing (which was actually a single threaded process) did not really work async unless you passed the server name every time thus creating multiple process (one per instrument).

Correct?

**Comment by MerlinSmiles** [comment]
@giulioungaretti The solution was to put everything on its own process, this has been removed so right now everything is happening sequentially, and wasting a lot of time, I guess the timing tests from my first post are still valid.

**Comment by giulioungaretti** [comment]
@MerlinSmiles  wrong :D  Now there is the option to use threads, for async operations.
Which requires thread safe instruments :D

**Comment by MerlinSmiles** [comment]
Ok wait i missed out on that, where is the issue / pr / description? Did you time it with the DMM's for example?
Awesome :)

**Comment by giulioungaretti** [comment]
@MerlinSmiles  https://github.com/QCoDeS/Qcodes/blob/master/qcodes/loops.py#L633

**Comment by MerlinSmiles** [comment]
doh!
Im pretty sure it solves this issue, will open a new one when something is not as expected

**Comment by giulioungaretti** [comment]
awesome !
