### ISSUE TITLE
IPInstrument._send() could not send all its data

### ISSUE THREAD

**Issue by nyxus** [QCoDeS/Qcodes#748]
I was browsing the instruments code and found out that in the `IPInstrument` class the `socket.send(...)` function is implemented wrongly:

```python
    def _send(self, cmd):
        data = cmd + self._terminator
        self._socket.send(data.encode())
```

This is what the documentation says about `socket.send(...)`:

> socket.send(bytes[, flags])
Send data to the socket. The socket must be connected to a remote socket. The optional flags argument has the same meaning as for recv() above. Returns the number of bytes sent. Applications are responsible for checking that all data has been sent; if only some of the data was transmitted, the application needs to attempt delivery of the remaining data. 
https://docs.python.org/3.6/library/socket.html

At this moment, if `send(...)` fails, only a part of the message is transmitted. Which will create strange bugs.

A better solution is to use `socket.sendall(...)` or as the example shows:
```python
    def mysend(self, msg):
        totalsent = 0
        while totalsent < MSGLEN:
            sent = self.sock.send(msg[totalsent:])
            if sent == 0:
                raise RuntimeError("socket connection broken")
            totalsent = totalsent + sent
```
https://docs.python.org/3.6/howto/sockets.html#socket-howto

**Comment by jenshnielsen** [comment]
Thanks for the report. I agree this is obviously wrong. Fixed in #719
