### ISSUE TITLE
Dont auto limit colorbar. 

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#751]
The user may have done this on purpose to filter outlier

* Replace wrappers in qdev-dk with call to new function
* Make autolimit of colorbars optional or disable it completely

**Comment by Dominik-Vogel** [comment]
If the purpose was to filter outliers we could consider implementing, this as a functionality. In my experience a really convenient way to automatically filter outliers is apply a percentile scale, eg setting the colorscale such that the upper and lower 1%  of the number of points are excluded.
