### ISSUE TITLE
Subplots with MatPlot

### ISSUE THREAD

**Issue by gzheng29** [QCoDeS/Qcodes#757]
MatPlot seems to have a subplot feature, but it's not obvious to use. Perhaps there could be a short tutorial on how to plot multiple heatmaps with certain figure sizes in a single figure.

**Comment by nulinspiratie** [comment]
I added the latest changes to how to use the subplots, so i can add some info in a tutorial. @WilliamHPNielsen Should this go in the main QCoDeS tutorial, or in something separate?

**Comment by WilliamHPNielsen** [comment]
@nulinspiratie, that's really nice of you! I think the `Tutorial.ipynb` should be left short so as to let newcomers get started quickly. You could start a new notebook called something like `Comprehensive Plotting How-To`. Then we'll (eventually) put all the advanced/non-standard plots in there.

**Comment by gzheng29** [comment]
Awesome guys, thanks a bunch!
