### ISSUE TITLE
Multiples validator only works for Ints

### ISSUE THREAD

**Issue by AdriaanRol** [QCoDeS/Qcodes#765]
The `Multiples(Ints)` validator checks if a give value is a multiple of some other value (the `divisor`). 

This validator only works for `Ints` and there is no reason for this. 

A perfectly valid example would be requiring for values to be multiples of 20ns. 

The current value would then be valid `40e-9` as this would return 0.0. Currently this will raise an error as 40e-9 (which is a multiple of 20e-9) raises an error as it is not an Int. I propose dropping the constraint of it having to be an Int.

**Comment by jenshnielsen** [comment]
Thats sensible enough but we will nede to be careful about the implementation 
as floating point math cannot be assumed to be distributive. For example 

```python
In [1]: divisor = (1/3)*1e-10
In [2]: print(((1/3)*1e-9)%divisor)
3.333333333333331e-11
```

**Comment by WilliamHPNielsen** [comment]
@AdriaanRol I'll put up an extra validator, `PermissiveMultiples`, for this on Monday.
