### ISSUE TITLE
README

### ISSUE THREAD

**Issue by peendebak** [QCoDeS/Qcodes#833]
The `README.rst` claims that some features are broken outside the notebook. Is this still valid? If so, could we document the features?

**Comment by lf19902001** [comment]
I also want to ask this question.

**Comment by WilliamHPNielsen** [comment]
I think in general it would be good to update the `README.rst`. I don't know if anyone feels like volunteering for that, @QCoDeS/core?

**Comment by jenshnielsen** [comment]
related to #839 too
