### ISSUE TITLE
RTO1024/RTO1000 scope driver issues

### ISSUE THREAD

**Issue by AdriaanRol** [QCoDeS/Qcodes#856]
I have found several problems with the RTO scope driver. 

1. The when using the HD mode on an RTO1024 the bandwidht get's set to 1MHz and cannot be changed from there. 
This would not be problematic if this mode was not needed but it is also used to set the dataformat which uses the same parameter. 

Observe the following difference and not the (spurious) staircase due to digitization in the left figure. 

![image](https://user-images.githubusercontent.com/6142932/32517253-1e69d472-c406-11e7-80bd-bc421a5c9c39.png)

Both are the same trace measured. The one on the right is measured by a little hack in the driver. 
The second trace contains a scaling error on the y-axis but I'm sure that can be fixed quite easilty. 
![image](https://user-images.githubusercontent.com/6142932/32517319-4e4e5352-c406-11e7-8372-369cce667340.png)

I added a screenshot from the scope itself as reference. 
![image](https://user-images.githubusercontent.com/6142932/32517336-623ff820-c406-11e7-802a-d3c9c33c31d3.png)

2. Recent QCoDeS updates make this driver give a warning upon instantiation. IMO this should be fixed. 
![image](https://user-images.githubusercontent.com/6142932/32517377-914e9216-c406-11e7-9e1c-06bc77b27956.png)

**Comment by AdriaanRol** [comment]
When using this workaround it is important to also use the following change for the rescaling of the data. 

![image](https://user-images.githubusercontent.com/6142932/32518174-18f63c1c-c409-11e7-88da-76a9bcd86096.png)

**Comment by WilliamHPNielsen** [comment]
Hi @AdriaanRol, thanks for catching this one. I don't have access to an instrument right now, but let's see if I can make sense of what is going on.

From how I understood the manual, one can not acquire in 16 bit unless the instrument is in high definition mode. Is you left figure really 16 bit with the high definition mode off? (nevermind the data _format_, are there really 2^16 unique values?) If so, then we might remove the `high_definition_state` paramater. If not, I think a real solution is to make the high definition mode not limit the bandwidth. Could you try using the `HDEFinition:BWIDth` command to see if you can set the high definition mode bandwidth. 

I am sorry that I did not realise that the high definition mode comes with a bandwidth of its own.

**Comment by AdriaanRol** [comment]
I just figured out how to increase the bandwidth when using HD mode. 

I think this should also be implemented when addressing this issue. 

Tested using : 
![image](https://user-images.githubusercontent.com/6142932/33663237-71146864-da8f-11e7-928b-bedf1fb97af7.png)
Where rto is an instance of the RTO instrument driver. 

Below is an excerpt of the manual (page 1059) 
![image](https://user-images.githubusercontent.com/6142932/33663301-b0c697a2-da8f-11e7-9b3d-1d865803e4e2.png)

**Comment by WilliamHPNielsen** [comment]
Yes, that's what I tried to hint at above. Glad that we agree 😄 

Do you want to make a PR adding this parameter? I can also do it, but it will not happen this week.

**Comment by WilliamHPNielsen** [comment]
Or actually, an RTO 1044 just landed on my desk for an entirely different reason. Let me seize the opportunity to fix this.

**Comment by AdriaanRol** [comment]
Awesome, looking forward to the PR!
