### ISSUE TITLE
Docstring and argument should be available by shift-tab in the notebook

### ISSUE THREAD

**Issue by MerlinSmiles** [QCoDeS/Qcodes#90]
Related to my last comment in #78.

From the user perspective, this is an important issue and will determine how effective users actually use the code.

The docstrings of functions have to somehow magically go through the processes stuff, but it is actually needed for all important things in the notebook, at any point, I as a user want to do shift tab and see what that function does.

The same goes for available arguments, I only figured out that `update=True` exists for the snapshot by digging through the code on my way to figure out where to implement it, we cannot expect this from a regular user.

**Comment by giulioungaretti** [comment]
This is probably been fixed along the way.
Qcodes had a *args, **kwargs abuse problem that we fixed little by tittle. 

@MerlinSmiles  you fixed it (8926f45aeb98ebce513739d6fecc51f88c19a635)
