### ISSUE TITLE
Custom parameters break datasaver (new dataset)

### ISSUE THREAD

**Issue by dmtvanzanten** [QCoDeS/Qcodes#902]
### Steps to reproduce
1.
```
pP = ParamSpec('P', 'number', label='Power', unit='W')

meas = Measurement()
meas.registerParameter(dac.ch1)  # register the first independent parameter
meas.registerParameter(pP)
meas.registerParameter(dmm.v1, setpoints=(dac.ch1,))  # now register the dependent oone

R = 10E6 // Voltage to current conversion
with meas.run() as datasaver:         
    for set_v in np.linspace(0, 25, 251):
        dac.ch1.set(set_v)
        get_v = dmm.v1.get()
        datasaver.addResult((dac.ch1, set_v),
                            (dmm.v1, get_v), ('P', set_v*get_v/R))
        
    dataid = datasaver.id  # convenient to have for plotting
```

### Expected behaviour
Data being saved including the calculated virtual parameter P.

### Actual behaviour
```
WARNING:qcodes.dataset.measurements:Could not commit to database; table name-1-27 has no column named P
Starting experimental run with id: 27
```
 Running the code with 
`datasaver.addResult((dac.ch1, set_v), (dmm.v1, get_v), (pP, set_v*get_v/R))`,
instead returns the following error
`WARNING:qcodes.dataset.measurements:Could not commit to database; near "(": syntax error Starting experimental run with id: 28`
FYI: I would prefer the latter syntax over the former.

### System
**operating system**

**qcodes branch**
feature/dataset

**qcodes commit**

**Comment by WilliamHPNielsen** [comment]
This was never supposed to work that way.

**Comment by jenshnielsen** [comment]
@WilliamHPNielsen This should probably raise then? There is a registerCustomParameter now right
