### ISSUE TITLE
internal data of String validator breaks AWG5014

### ISSUE THREAD

**Issue by peendebak** [QCoDeS/Qcodes#921]
In PR #859 new variables `._valid_values` are added to the `String` validator. The default validator object `qcodes.utils.validators.String()` now has a size of 1 GB.

The `AWG5014` driver uses the `String` validator four times, so the driver now is 4GB. If one reloads the driver 8 GB is occupied, which crashes a system with limited amount of RAM.

https://github.com/QCoDeS/Qcodes/blob/master/qcodes/instrument_drivers/tektronix/AWG5014.py#L326

I am not sure how the `._valid_values` field is used, but I think it does not make a lot of sens for a `String`. Can we set the `_valid_values` field to `None` as a solution?

@WilliamHPNielsen @AdriaanRol @jenshnielsen @lucblom

**Comment by WilliamHPNielsen** [comment]
Woops... Luckily the fix is straightforward. 

I can even disclose that the `_valid_values` are not currently used for anything, but the great plan is to eventually use them to auto-generate simulated instruments from an instruments parameters.
