### ISSUE TITLE
Drop support for python 3.5

### ISSUE THREAD

**Issue by WilliamHPNielsen** [QCoDeS/Qcodes#926]
Is there any reason to keep supporting python 3.5? The new dataset will be incompatible with python 3.5 (unless we do a fair bit of rewriting), and all new user are installing Anaconda with python 3.6 these days.

Does anyone know of a good reason to not move forward? Would it break something for anyone?

@QCoDeS/core (but I'd like to hear from everyone)

**Comment by jenshnielsen** [comment]
👍  from me. I suggest raising this on slack too

**Comment by peendebak** [comment]
@WilliamHPNielsen Many of our systems are still on python 3.5. I would like to keep qcodes compatible for some time if possible. Not sure if something would break, but I am not keen on trying.

**Comment by WilliamHPNielsen** [comment]
@peendebak Good to know. I'm glad we're discussing this now, then. I think we are going to drop python 3.5 support as soon as we can, the question is only when that is. It would be natural to do it in connection with merging the dataset PR, which is currently believed to happen around the end of January. Is it unrealistic for you to transition over to python 3.6 in the course of one month?

**Comment by WilliamHPNielsen** [comment]
This happened when #806 was merged. We no longer support python 3.5
