### ISSUE TITLE
Finish Context manager

### ISSUE THREAD

**Issue by jenshnielsen** [QCoDeS/Qcodes#930]

**Comment by WilliamHPNielsen** [comment]
We still need to settle on an API for adding QCoDeS parameters as well as custom parameters and to hit it heavily with tests.

**Comment by WilliamHPNielsen** [comment]
Some work items:
- [ ] Switch methods names from camelCase to snake_case
- [ ] Make `add_result` call signature match the one one level deeper in the API
- [ ] Add `register_paramspec` function (to add custom parameter)
- [ ] Agree on measurement object hierarchy
- [ ] tests
- [ ] more tests

**Comment by WilliamHPNielsen** [comment]
@QCoDeS/core I think the context manager is done, at least for a beta version. Comments and pointing out of blunders most welcome.

I'll put up an example notebook using some actual instruments including ones with `ArrayParameters`.

**Comment by WilliamHPNielsen** [comment]
Closing this issue as it has outlived its purpose as a TO-DO point during a sprint.
