### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by MerlinSmiles** [QCoDeS/Qcodes#98]
Has anyone here experience on logging in packages like qcodes? Including multiprocessing?

I see some logging is spread out in some of the files, one resource I read is this http://pythonsweetness.tumblr.com/post/67394619015/use-of-logging-package-from-within-a-library
Which has some interesting comments on not using the `root` logger from within a package.

My intention last night was to route all logging from within qcodes to a logging handler defined in the notebook. In some parts it worked fine, and in others it failed completely.

I.e. I wanted those negative delays to log into that logging handler, currently they written to the process `stdout` or `sterr` and the starting process reads those in, basically removing a lot of logging information that comes with it.

Does anyone know how to organize this logging functionality so that I can capture **all** logging from qcodes?

**Comment by jenshnielsen** [comment]
QCoDeS does a fair amount of logging using the standard library. Seems to be working file
